mongodb/openapi

- .github/actionlint-matcher.json
- .github/workflows/code-health-tools.yml
- tools/cli/.golangci.yml
- tools/cli/Makefile
- tools/cli/internal/cli/merge/merge.go
Ticket: CLOUDP-236398
Description: Add golangci to the repo
> CLOUDP-236398: Adding golangci and code-health action

- .github/CODEOWNERS
- .github/pull_request_template.md
This PR adds the PR template to the repo.
> feat: add PR template to repo

- .gitignore
- tools/postman/Makefile
- tools/postman/package-lock.json
- tools/postman/package.json
- tools/postman/scripts/convert-to-collection.sh
- tools/postman/scripts/fetch.sh
This adds make target and bash script that Converts the OpenAPI spec file to a Postman Collection file.
node_modules folder is ignored.
_Jira ticket:_ CLOUDP-262012
> CLOUDP-262012: Convert from OpenAPI Spec to Postman Collection

- tools/cli/internal/cli/flag/flag.go
- tools/cli/internal/cli/merge/merge.go
- tools/cli/internal/cli/usage/usage.go
_Jira ticket:_ CLOUDP-262703:
Add support for `x-xgen-sha` to the `foascli merge` command
> CLOUDP-262703: Add x-xgen-sha flag to GenerateAtlasOpenApiSpecTool

- .github/workflows/optional-spec-validations.yml
- .github/workflows/release-spec-prod.yml
- .github/workflows/required-spec-validations.yml
This PR proposes the following changes:
1) splits the validations to different workflows to allow us to reuse them when running in other environments
2) adds the split step to the release workflow
I tested the changes in a fork: https://github.com/andreaangiolillo/openapi-test/actions/runs/10061894444
> CLOUDP-263265: Add step to split the FOAS to versions

- .github/workflows/optional-spec-validations.yml
- .github/workflows/release-spec-prod.yml
- .github/workflows/required-spec-validations.yml
This PR adds the logic to retrieve the FOASMetadata from APIx s3 bucket.
I tested my changes in a fork: https://github.com/andreaangiolillo/openapi-test/actions/runs/10096226482
I plan to move the FOAS generation logic to another workflow that is called from the main one similar to the validations.
> CLOUDP-263186: Add Logic to retrieve the FOASMetadata from APIx s3 bucket

- tools/cli/internal/cli/split/split.go
- tools/cli/internal/cli/versions/versions.go
- tools/cli/internal/cli/versions/versions_test.go
- tools/cli/internal/openapi/filter/filter.go
- tools/cli/internal/openapi/filter/hidden_envs.go
- tools/cli/internal/openapi/filter/hidden_envs_test.go
- tools/cli/internal/openapi/versions.go
- tools/cli/internal/openapi/versions_test.go
- tools/cli/test/data/openapi-foas-dev.json
- tools/cli/test/data/openapi-foas-dev.yaml
The PR proposes the following changes:
- Fixes a bug in the HiddenEnvs filter where we were not deleting the ContentType
- Updates the split command to remove the hidden env before getting the valid version
> fix: fixes the filtering logic

- .github/scripts/download_specs.sh
- .github/scripts/generate_federated_spec.sh
- .github/workflows/generate-openapi.yml
- .github/workflows/optional-spec-validations.yml
- .github/workflows/release-spec-prod.yml
- .github/workflows/required-spec-validations.yml
This PR refactors gh release action to use a sub-workflow to generate foas.
I tested my changes in a fork https://github.com/andreaangiolillo/openapi-test/actions/runs/10097323012
> refactor: refactor gh release action to use a subworkflow to generate foas

- .spectral.yaml
CLOUDP-260965
Add spectral rule to check for the correct format of `x-xgen-hidden-env`
I tested locally by adding the `x-xgen-hidden-env` extension with the wrong format to multiple places (operation, response and response-body)
```bash
spectral lint ./tools/cli/test/data/openapi-foas-dev.yaml --ruleset=.spectral.yaml --format stylish --display-only-failures
/Users/andrea.angiolillo/workspace/openapi/tools/cli/test/data/openapi-foas-dev.yaml
33350:47  error  x-xgen-hidden-env-format  Ensure x-xgen-hidden-env extension has the correct format. https://go/openapi-hidden-extension  paths./api/atlas/v2/groups/{groupId}/clusters.get.responses[200].content.application/vnd.atlas.2025-01-01+json.x-xgen-hidden-env
33514:43  error  x-xgen-hidden-env-format  Ensure x-xgen-hidden-env extension has the …
```
> CLOUDP-260965: Check that the extention x-xgen-hidden has the correct format

- tools/postman/scripts/transform-for-api.sh
- Add Environment variable to remove all generate request and response bodies
- Uses jq to set request bodies to an empty object
- Use jq to set response bodies to an empty string (due to constraints with empty body responses in Postman)
- This keeps the possible response codes but removes the possibly incorrect bodies
Tested on private postman upload
_Jira ticket:_ CLOUDP-264585
> CLOUDP-264585: Add toggle to remove generated request and response bodies

- .github/scripts/split_spec.sh
- .github/workflows/release-spec-prod.yml
- .github/workflows/release-spec-runner.yml
- .github/workflows/release-spec.yml
This PR fixes an issue with the staging release process where we are using `staging` instead of `stage` when running `foascli split` command
> fix: update the foas staging release to use `stage` instead of staging when using `foascli split`

- .github/scripts/branded_preview.sh
- .github/workflows/release-spec-prod.yml
- .github/workflows/release-spec.yml
This PR updates the FOAS release process to generate a `branded_preview.html` using the `foascli versions` command similar to what we have in evergreen
File generated by running the script locally using target_env=dev
```html
<!DOCTYPE html>
<html lang="en">
<body>
<h2>Preview docs for:</h2>
<ul>
<li><a href='https://www.mongodb.com/docs/openapi/preview/?src=https://raw.githubusercontent.com/mongodb/openapi/dev/openapi/v2.json' target="_blank">v2.json</a></li><li><a href='https://www.mongodb.com/docs/openapi/preview/?src=https://raw.githubusercontent.com/mongodb/openapi/dev/openapi/v2.yaml' target="_blank">v2.yaml</a></li><li><a href='https://www.mongodb.com/docs/openapi/preview/?src=https://raw.githubusercontent.com/mongodb/openapi/dev/openapi/v2/openapi-2023-01-01.json' …
```
> feat: add branded_preview to the FOAS release process

- tools/cli/internal/cli/changelog/changelog.go
- tools/cli/internal/cli/changelog/changelog_test.go
- tools/cli/internal/cli/changelog/create.go
- tools/cli/internal/cli/flag/flag.go
- tools/cli/internal/cli/root/openapi/builder.go
- tools/cli/internal/cli/usage/usage.go
- tools/cli/internal/test/test.go
_Jira ticket:_ CLOUDP-225858
This PR creates the skeleton of the changelog command
```bash
./bin/foascli changelog create --help                                     
Generate the changelog for the OpenAPI spec.
Usage:
foascli changelog create -b path_folder -r path_folder --dry-run ... [flags]
Aliases:
create, generate
Flags:
-b, --base string       Base folder where the command will store the output.
-d, --dry-run           Dry run mode. The command will not write any files.
-h, --help              help for create
-r, --revision string   Folder where the command will store the output.
```
> CLOUDP-225858: add changelog command skeleton

- tools/cli/go.mod
- tools/cli/go.sum
- tools/cli/internal/cli/changelog/create.go
- tools/cli/internal/cli/flag/flag.go
- tools/cli/internal/cli/usage/usage.go
- tools/cli/internal/openapi/changelog.go
- tools/cli/internal/openapi/openapi.go
- tools/cli/internal/openapi/openapi3.go
- tools/cli/internal/openapi/openapi3_test.go
_Jira ticket:_ CLOUDP-26613
This PR adds support for the first step of the API Changelog which is normalizing the input specs.
> CLOUDP-26613: add normalization to the changelog

- tools/cli/internal/cli/changelog/create.go
- tools/cli/internal/openapi/changelog.go
- tools/cli/internal/openapi/oasdiff.go
- tools/cli/internal/openapi/openapi.go
- tools/cli/internal/openapi/openapi3.go
_Jira ticket:_ CLOUDP-266130
This PR adds changelog core logic to FOAS CLI
```bash
./bin/foascli changelog create -b ~/Downloads/test/base -r ~/Downloads/test/revision -e ~/Downloads/test/exceptions.yaml                         
Printing the checks
[
{
"Attributes": null,
"Id": "api-schema-removed",
"Args": [
"AzureHardwareSpec20250101"
],
"Comment": "",
"Level": 3,
"Component": "schemas",
"SourceFile": "",
"SourceLine": 0,
"SourceLineEnd": 0,
"SourceColumn": 0,
"SourceColumnEnd": 0
},
.....
]
```
> CLOUDP-266130: Add changelog core logic

- tools/cli/internal/changelog/changelog.go
- tools/cli/internal/changelog/merge.go
- tools/cli/internal/changelog/merge_test.go
- tools/cli/internal/changelog/outputfilter/operationconfig.go
- tools/cli/internal/changelog/outputfilter/operationconfig_test.go
- tools/cli/internal/changelog/outputfilter/outputfilter.go
- tools/cli/internal/cli/changelog/create.go
- tools/cli/test/data/changelog/changelog.json
> CLOUDP-266992: Migrate changes_processor.py logic to foascli

- tools/cli/internal/changelog/changelog.go
- tools/cli/internal/changelog/changelog_test.go
- tools/cli/internal/changelog/manual_entry.go
- tools/cli/internal/changelog/manual_entry_test.go
- tools/cli/internal/changelog/merge.go
- tools/cli/internal/changelog/merge_test.go
- tools/cli/internal/changelog/outputfilter/outputfilter.go
- tools/cli/internal/changelog/sunset.go
- tools/cli/internal/changelog/sunset_test.go
- tools/cli/internal/cli/changelog/create.go
_Jira ticket:_ CLOUDP-266446
This PR migrates the code in `sunset_endpoints.py` and `changelog_manual_entries.py`
> CLOUDP-266446: this PR adds the sunset and manual entry logic to foascli changelog

- tools/cli/internal/changelog/changelog.go
- tools/cli/internal/changelog/changelog_test.go
- tools/cli/internal/changelog/manual_entry.go
- tools/cli/internal/changelog/manual_entry_test.go
- tools/cli/internal/changelog/merge.go
- tools/cli/internal/changelog/merge_test.go
- tools/cli/internal/changelog/outputfilter/operationconfig.go
- tools/cli/internal/changelog/outputfilter/outputfilter.go
- tools/cli/internal/changelog/sunset.go
- tools/cli/internal/changelog/sunset_test.go
- tools/cli/internal/cli/changelog/create.go
- tools/cli/internal/openapi/oasdiff.go
- tools/cli/internal/openapi/openapi3.go
_Jira ticket:_ CLOUDP-267021
This PR migrates the changeAll logic (`_generate_changelog`  in **generate_changelog.py**)  to foascli
> CLOUDP-267021: Add changelog-all logic to the foascli

- tools/postman/collection-description.md
- tools/postman/scripts/transform-for-api.sh
- Set the collection description equal to markdown file.
- Tested locally and uploaded to a private Postman account
- Markdown provided by Jeff Vincent from Docs team 
_Jira ticket:_ CLOUDP-267379
> CLOUDP-267379: Add collection description to generated collections

- .github/workflows/release-postman.yml
- tools/postman/Makefile
- tools/postman/scripts/upload-collection.sh
- Last [Postman Release workflow run failed](https://github.com/mongodb/openapi/actions/runs/10418257689/attempts/1)
- It was caused by a 504 error into a 400 error upon retry
- Upon rerun of the workflow it succeeded without the OAS changing.
- Added retry on 400 error 
- Also separated transformation and upload into separate steps 
_Jira ticket:_ CLOUDP-268216
> CLOUDP-268216: Fix failing postman release run

- .github/scripts/download_specs.sh
- .github/scripts/generate_federated_spec.sh
This PR adds `x-xgen-sha` to the generated openapi spec. The release logic uses the mms deployed sha as `x-xgen-sha` for the FOAS.
I tested my changes in a fork: https://github.com/andreaangiolillo/openapi-test/pull/38/files
> feat: add `x-xgen-sha` to the generated federated open api spec

- .github/workflows/release-postman.yml
- .github/workflows/release-spec-runner.yml
- .github/workflows/release-spec.yml
- tools/postman/collection-description.md
- Change release postman workflow from being triggered on Prod release PR merge to instead be called by the release openapi workflow
_Jira ticket:_ CLOUDP-269114
> CLOUDP-269114: Change release postman trigger

- tools/cli/internal/cli/changelog/metadata/create.go
This PR fixes a bug with the `changelog metadata create` command where the command was saving bytes into the output file when the -o flag was used.
I tested my changes locally.
```bash
./bin/foascli changelog metadata create --sha e624d716e86f6910757b60cefdf3aa3181582d38 --versions=2024-01-01,2024-09-22 --output metadata.json
2024/08/22 12:06:24
File was saved in 'metadata.json'.
cat metadata.json  
"ewogICJydW5EYXRlIjogIjIwMjQtMDgtMjIiLAogICJzcGVjUmV2aXNpb24iOiAiZTYyNGQ3MTZlODZmNjkxMDc1N2I2MGNlZmRmM2FhMzE4MTU4MmQzOCIsCiAgInNwZWNSZXZpc2lvblNob3J0IjogImU2MjRkNzE2ZTg2IiwKICAidmVyc2lvbnMiOiBbCiAgICAiMjAyNC0wMS0wMSIsCiAgICAiMjAyNC0wOS0yMiIKICBdCn0="
```
```bash
./bin/foascli changelog metadata create --sha e624d716e86f6910757b60cefdf3aa3181582d38 --versions=2024-01-01,2024-09-22 --output …
```
> fix: update `changelog metadata create` command to save the correct struct

- .github/ISSUE_TEMPLATE/GH_ACTION_ISSUE_TEMPLATE.md
- .github/scripts/create_jira_ticket.sh
- .github/workflows/failure-handler.yml
- .github/workflows/issue.yml
- .github/workflows/release-changelog.yml
- .github/workflows/release-cli.yml
- .github/workflows/release-postman.yml
- .github/workflows/release-spec-runner.yml
- .github/workflows/release-spec.yml
_Jira ticket:_ CLOUDP-269500
This PR adds the logic to handle failures in the release process.
Logic:
- Check if there is already an issue for it
- If not, file a new GH issue in the repo
- Create a new Jira ticket
- Append the Jira ticket to the GH issue
I tested the logic in a fork: https://github.com/andreaangiolillo/openapi-test/issues/54
> CLOUDP-269500: Add logic to create jira ticket when we file an issue

- tools/cli/internal/changelog/changelog.go
- tools/cli/internal/changelog/merge_test.go
- tools/cli/internal/cli/changelog/changelog_test.go
- tools/cli/internal/cli/changelog/convert/convert.go
- tools/cli/internal/cli/changelog/convert/slack.go
- tools/cli/internal/cli/changelog/convert/slack_test.go
- tools/cli/internal/cli/flag/flag.go
- tools/cli/internal/cli/usage/usage.go
CLOUDP-225860
This PR defines a new `changelog convert slack` command to convert the changelog to a format that can be used via Slack API.
Create a GH action that uses the command to send weekly summary 
I tested my changes locally using [slack staging](https://mdb-pc-staging.slack.com/archives/C07JPULFAAE/p1724778625960529)
> CLOUDP-225860: add new changelog convert command to create a slack summary

- .spectral.yaml
Add spectral lint to validate custom methods
Example:
```shell
INFO: Build completed successfully, 1 total action
Running spectral linter
6.11.1
- linting /Users/bianca.lisle/workplace/mms/server/openapi/services/openapi-mms.yaml
/<redacted>/openapi-mms.yaml
1640:69  error  no-slash-before-custom-method  Ensure that paths do not contain a '/' immediately before a custom method (e.g., ':applyItem').  paths./api/atlas/v2/orgs/{orgId}/invoices/{invoiceId}/lineItems/:search
```
> chore: Add spectral lint rule

- .spectral.yaml
This reverts commit 744edaa878e98e46a266a07e84d1f651c0e1b8fc.
Foas Release process started to fail after #183 was merged. Reverting the PR for now.
> fix: Revert "chore: Add spectral lint rule (#183)

- tools/cli/internal/cli/changelog/convert/slack.go
- tools/cli/internal/cli/changelog/convert/slack_test.go
This PR updates the format of the Changelog report that we send via slack message to move backward compatible as the last item
> feat: update changelog convert format to move Backward Compatible as last item

- tools/cli/internal/cli/changelog/convert/slack.go
- tools/cli/internal/cli/changelog/convert/slack_test.go
update changelog convert format to include Change Type
> feat: update changelog convert format to include Change Type

- .github/workflows/required-spec-validations.yml
- .github/workflows/spectral-lint.yml
- tools/spectral/.spectral.yaml
- tools/spectral/Makefile
_Jira ticket:_ [CLOUDP-271224](https://jira.mongodb.org/browse/CLOUDP-271224)
> CLOUDP-271224: Add spectral rules and validation for soa migration

- .github/workflows/spectral-lint.yml
- tools/spectral/.spectral.yaml
- tools/spectral/README.md
- re-add linting rule
- add docs about the spectral updates
> chore: Add docs

- .github/workflows/failure-handler.yml
Fixes: #235 #233 #232 
Our failure handler is creating a new issue if the check to see whether an issue already exists fails. See [Logs](https://github.com/mongodb/openapi/actions/runs/11076277766/job/30780874487#step:3:17). 
This PR updates the logic to halt execution when it’s unclear whether an issue has already been created.
> fix: stop issue creating in the event of an issue with GH APIs

- tools/cli/test/data/changelog/new-api-version/base/openapi-2023-01-01.json
- tools/cli/test/data/changelog/new-api-version/base/openapi-2023-02-01.json
- tools/cli/test/data/changelog/new-api-version/base/openapi-2023-10-01.json
- tools/cli/test/data/changelog/new-api-version/base/openapi-2023-11-15.json
- tools/cli/test/data/changelog/new-api-version/base/openapi-2024-05-30.json
- tools/cli/test/data/changelog/new-api-version/revision/openapi-2023-01-01.json
- tools/cli/test/data/changelog/new-api-version/revision/openapi-2023-02-01.json
- tools/cli/test/data/changelog/new-api-version/revision/openapi-2023-10-01.json
- tools/cli/test/data/changelog/new-api-version/revision/openapi-2023-11-15.json
- tools/cli/test/data/changelog/new-api-version/revision/openapi-2024-05-30.json
- tools/cli/test/data/changelog/new-api-version/revision/openapi-2024-08-05.json
- tools/cli/test/data/changelog/same-api-version/base/openapi-2023-01-01.json
- tools/cli/test/data/changelog/same-api-version/base/openapi-2023-02-01.json
- tools/cli/test/data/changelog/same-api-version/base/openapi-2023-10-01.json
- tools/cli/test/data/changelog/same-api-version/base/openapi-2023-11-15.json
- tools/cli/test/data/changelog/same-api-version/base/openapi-2024-05-30.json
- tools/cli/test/data/changelog/same-api-version/base/openapi-2024-08-05.json
- tools/cli/test/data/changelog/same-api-version/revision/openapi-2023-01-01.json
- tools/cli/test/data/changelog/same-api-version/revision/openapi-2023-02-01.json
- tools/cli/test/data/changelog/same-api-version/revision/openapi-2023-10-01.json
- tools/cli/test/data/changelog/same-api-version/revision/openapi-2023-11-15.json
- tools/cli/test/data/changelog/same-api-version/revision/openapi-2024-05-30.json
- tools/cli/test/data/changelog/same-api-version/revision/openapi-2024-08-05.json
This PR fixes the changelog e2e tests to extend the sunset date of the specs used in the e2e tests to 2099.
Conversation: https://github.com/mongodb/openapi/pull/238#discussion_r1789986879
> CLOUDP-277321: extend sunset date on e2e spec files

- tools/spectral/.spectral.yaml
_Jira ticket:_ CLOUDP-271222
- Updates spectral linting for the x-xgen-soa-migration annotation values updated in the technical design according to SRE recommendation.
> CLOUDP-271222: Update spectral linting

- .github/workflows/spectral-lint.yml
- tools/spectral/.spectral.yaml
Reverts mongodb/openapi#251
Validation is failing with the last changes: https://github.com/mongodb/openapi/issues/253
> Revert "CLOUDP-274986: Update OAS security validation for global security"

- tools/spectral/.spectral.yaml
Removing rule `xgen-no-security` for the changes in the OAS setting the security globally. After the OASes have been updated in all environments we can introduce the new rule here.
_Jira ticket: [CLOUDP-274986](https://jira.mongodb.org/browse/CLOUDP-274986)
> CLOUDP-274986: Remove rule for security to be set on all operations

- .github/pull_request_template.md
- tools/spectral/.spectral.yaml
- tools/spectral/README.md
Updating the README for spectral changes to guide MMS/openapi maintainers depending on the change to the linting/OAS and changes needed to propagate to MMS.
_Jira ticket: [CLOUDP-278403](https://jira.mongodb.org/browse/CLOUDP-278403)
> CLOUDP-278403: Spectral README update for linting/OAS changes

- .github/workflows/required-spec-validations.yml
- package.json
- tools/cli/internal/breakingchanges/exemptions.go
- tools/cli/internal/changelog/outputfilter/hide.go
> CLOUDP-274733: Fix flaky test

- tools/spectral/.spectral.yaml
> CLOUDP-278627: Update linting

- tools/spectral/.spectral.yaml
Validates that security is not set on individual endpoints except for unauth overrides.
_Jira ticket:_ [CLOUDP-278402](https://jira.mongodb.org/browse/CLOUDP-278402)
Will ensure OAS validation passes for all envs after PR is merged.
> CLOUDP-278402: Add security override validation

- tools/cli/internal/openapi/oasdiff.go
- tools/cli/internal/openapi/oasdiff_test.go
- tools/cli/internal/openapi/paths.go
> CLOUDP-284014: Check soa migration in external path

- tools/cli/internal/changelog/outputfilter/squash.go
_Jira ticket:_ CLOUDP-283505
Changelog generation failed with:
```shell
2024/11/04 16:14:51 Marked 414 changes hidden from the changelog.
Error: the pattern for response-property-enum-value-removed message was changed. Expecting exactly 2 values between apostrophes: removed the '' enum value from the 'results/items/oneOf[subschema #4: Host Metric Alerts]/currentValue/units' response property
```
However the info is valid, since there was an empty enum in the OpenAPI specification, see https://github.com/10gen/mms/pull/113043.
This PR updates the Regex so that we allow empty values.
> CLOUDP-283505: Allow empty removals

- tools/cli/internal/changelog/outputfilter/hide.go
- Updates the counter since we continue once we detect its marked to be hidden already
> chore: Update hiddenEntries counter

- tools/cli/internal/changelog/outputfilter/squash.go
- tools/cli/internal/changelog/outputfilter/squash_test.go
_Jira ticket:_ CLOUDP-279336
Similar to this: https://github.com/10gen/mms/blob/2bdd398c7ede9d7d1e58519c6931fb1dbae13a36/scripts/api_versioning/changelog/generate_changelog.py#L197-L204
As part of investigating exemptions, I also noticed we weren't accounting for hiddenFromChangelog values while squashing, which could end up overriding the hide value. I'm following a similar logic to the one in current changelog above to fix it and updated all tests.
> CLOUDP-279336: Avoid that squashing overrides hideFromChangelog

- changelog/changelog.json
_Jira ticket:_ CLOUDP-283830
Fixes changelog manually, until we figure out why it wasn't picked up in https://jira.mongodb.org/browse/CLOUDP-284672.
> CLOUDP-283830: Add missing changelog entries

- .github/workflows/api-versions-reminder.yml
1. Adds a link to the checklist 
2. Adds [API Platform] to the ticket title
> chore: Add minor details to the new version ticket

- tools/spectral/.spectral.yaml
> CLOUDP-284437: Add Spectral rule to ensure operationId uses camelcase

- .github/workflows/release-postman.yml
- tools/postman/README.md
Minor drive by improvements to README.md while I'm reviewing the feature:
- Fixed headings and their placement (all high level info is first and then local setup second)
- Added info about automation (missing)
- Added link to the collections production.
> CLOUDP-278958: improve postman documentation

- .github/workflows/release-postman.yml
- tools/postman/Makefile
- tools/postman/README.md
- tools/postman/scripts/transform-for-api-test.sh
_Jira ticket:_ CLOUDP-278958
Adding test to the customization mechanism we use to track possible regressions and issues when postman tooling is updated.
Releases will require tests to pass. I intentionally made test simple to cover happy path/critical changes only.  
Transformation engine is currently done as set of bash jq commands that are tricky to test and validate. 
Transformation files are not committed to the repository and visible during PRs.
We release postman automatically (postman does validation for correctness on backend) but it does not validate our customizations. 
- Run locally:
```
▶ make transform_collection_test
./scripts/transform-for-api-test.sh
~/Projects/sandbox/openapi/tools/postman/tmp ~/Projects/sandbox/openapi/tools/postman
Test Passed: Query params disabled …
```
> CLOUDP-278958: trasformation test

- tools/cli/internal/openapi/errors/merge_conflict_error.go
- tools/cli/internal/openapi/oasdiff.go
- tools/cli/internal/openapi/openapi3.go
- tools/cli/test/e2e/cli/merge_test.go
_Jira ticket:_ [CLOUDP-276602](https://jira.mongodb.org/browse/CLOUDP-276602)
This PR proposes to update the conflict error messages to include the Base and external spec locations to help debug where the issue is.
> CLOUDP-276602: FOASCLI: Improve the error message in the event of conflicts

- .github/workflows/code-health-tools.yml
- .github/workflows/spectral-lint.yml
- tools/spectral/ipa/__tests__/utils/resourceEvaluation.test.js
- Run IPA validation on PRs when there are changes to `/tools` (`js-test`)
- Run Jest unit tests on PRs when there are changes to `/tools` (`IPA validation action`). Should not fail as the rules are currently warning
_Jira ticket:_ [CLOUDP-290332](https://jira.mongodb.org/browse/CLOUDP-290332)
Testing:
- Example [fail run](https://github.com/mongodb/openapi/actions/runs/12355771014/job/34480142676?pr=311) for js-tests
- Example [IPA validations run](https://github.com/mongodb/openapi/pull/311/checks?check_run_id=34480205762) with warnings (expected)
> CLOUDP-290332: Run IPA validation and Jest tests as workflow

- tools/spectral/ipa/__tests__/eachPathAlternatesBetweenResourceNameAndPathParam.test.js
- tools/spectral/ipa/__tests__/eachResourceHasGetMethod.test.js
- tools/spectral/ipa/__tests__/exceptionExtensionFormat.test.js
- tools/spectral/ipa/__tests__/utils/exceptions.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-005.yaml
- tools/spectral/ipa/rulesets/functions/eachPathAlternatesBetweenResourceNameAndPathParam.js
- tools/spectral/ipa/rulesets/functions/eachResourceHasGetMethod.js
- tools/spectral/ipa/rulesets/functions/exceptionExtensionFormat.js
- tools/spectral/ipa/rulesets/functions/utils/exceptions.js
- tools/spectral/ipa/rulesets/functions/utils/resourceEvaluation.js
Adds ability to ignore API components with IPA exception extensions to existing IPA rules:
- `xgen-IPA-104-resource-has-GET`
- `xgen-IPA-102-path-alternate-resource-name-path-param`
Also added a IPA rule validation `xgen-IPA-005-exception-extension-format` to check the format of any `x-xgen-IPA-exception` extensions. This rule does not accept exceptions, and should not.
_Jira ticket:_ [CLOUDP-288860](https://jira.mongodb.org/browse/CLOUDP-288860)
- Added tests for existing rules to validate that the component is ignored when an `x-xgen-IPA-exception` extension is present with the corresponding rule name
- Added tests for the new `xgen-IPA-005-exception-extension-format` rule to validate that it catches invalid exception extensions
- Unit test for `hasException` helper function
> CLOUDP-288860: Support IPA exception and validate exception extensions

- tools/spectral/ipa/__tests__/eachCustomMethodMustBeGetOrPost.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-109.yaml
- tools/spectral/ipa/rulesets/functions/eachCustomMethodMustBeGetOrPost.js
_Jira ticket:_ [CLOUDP-287245](https://jira.mongodb.org/browse/CLOUDP-287245)
Implements a rule that the HTTP method for custom methods must be either GET or POST (https://docs.devprod.prod.corp.mongodb.com/ipa/109).
> CLOUDP-287245: IPA-109: Validate custom method must be GET or POST

- eslint.config.mjs
- package-lock.json
- package.json
- tools/spectral/ipa/rulesets/functions/eachPathAlternatesBetweenResourceNameAndPathParam.js
- tools/spectral/ipa/rulesets/functions/eachResourceHasGetMethod.js
Added eslint plugin to check that imports have .js extensions. No .js extension will cause issues in external repos importing the spectral rulesets with custom .js functions.
_Jira ticket:_ [CLOUDP-288860](https://jira.mongodb.org/browse/CLOUDP-288860)
> CLOUDP-288860: Require .js extension on imports

- .github/workflows/release-spec-runner.yml
> fix: add permission to parent workflow

- tools/spectral/ipa/__tests__/exceptionExtensionFormat.test.js
- tools/spectral/ipa/__tests__/utils/exceptions.test.js
- tools/spectral/ipa/rulesets/functions/exceptionExtensionFormat.js
Updated the spec with a change to the exception format, now the exceptions are formatted as follows:
```
"x-xgen-IPA-exception": {
"xgen-IPA-104-resource-has-GET": "Legacy API, not used by infrastructure-as-code tooling",
"xgen-IPA-105-resource-has-LIST": "Legacy API, not used by infrastructure-as-code tooling"
},
```
Previously: 
```
"x-xgen-IPA-exception": {
"xgen-IPA-104-resource-has-GET": {
"reason": "Legacy API, not used by infrastructure-as-code tooling"
},
"xgen-IPA-105-resource-has-LIST": {
"reason": "Legacy API, not used by infrastructure-as-code tooling"
}
},
```
- Updated the exception format validation to validate the new format
- Updated exceptions in tests
_Jira ticket:_ [CLOUDP-288860](https://jira.mongodb.org/browse/CLOUDP-288860)
> CLOUDP-288860: Update IPA exception format

- tools/spectral/ipa/__tests__/eachEnumValueMustBeUpperSnakeCase.test.js
- tools/spectral/ipa/rulesets/functions/eachEnumValueMustBeUpperSnakeCase.js
- tools/spectral/ipa/rulesets/functions/utils/componentUtils.js
In scope of _Jira ticket:_  [CLOUDP-291457](https://jira.mongodb.org/browse/CLOUDP-291457)
According to the [levels](https://docs.google.com/document/d/1hcYKgnD7FUGII-3BP4TgiBc9rDcNyd2LMuzbxqFUl1Q/edit?tab=t.0#bookmark=id.uhmnmfhntsru) defined in IPA Validations Framework Technical Design document, exceptions can be applied at the **Schema** or **Schema Property** level. 
Changes in this PR:
- Enums defined directly within a schema and those defined for a schema property are now evaluated separately.
- Error messages now identify the schema or schema property responsible for the rule violation, aligning with the level at which exceptions are defined.
- Example of updated error message:
Rule Name: `xgen-IPA-123-enum-values-must-be-upper-snake-case`
Error Message: `enum[0]:bits enum value …
> CLOUDP-291457: IPA-123 SchemaPath and Error Message Fix

- tools/spectral/ipa/__tests__/eachEnumValueMustBeUpperSnakeCase.test.js
- tools/spectral/ipa/rulesets/functions/eachEnumValueMustBeUpperSnakeCase.js
In scope of _Jira ticket:_ [CLOUDP-291457](https://jira.mongodb.org/browse/CLOUDP-291457)
This PR addresses the handling of exceptions defined on array schema definitions. Specifically, exceptions applied at the schema level preceding `items.enum` are not properly matched.
Changes:
- Updated the logic to remove enum from the path when it directly follows items.
- This ensures that exceptions defined at the array schema level (before items.enum) are correctly recognized during validation.
> CLOUDP-291457: IPA-123 ArraySchema fix

- package-lock.json
- package.json
- tools/spectral/ipa/__tests__/__helpers__/testRule.js
- tools/spectral/ipa/__tests__/singletonHasNoId.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-113.yaml
- tools/spectral/ipa/rulesets/functions/singletonHasNoId.js
- tools/spectral/ipa/rulesets/functions/utils/methodUtils.js
Adds rule for IPA 113: "Singleton resources must not have a user-provided or system-generated ID".
- For singleton resources checks the fields in the response for the GET method, if there is a field `id` or `_id` it returns a validation error
- Ignores paginated or array responses
Drive-by:
- Improvement of the test hook to only create a spectral instance with the specific rule that is tested, reduces the number of rules that spectral will try to validate in one test run
Current offenders:
```
warning  xgen-IPA-113-singleton-must-not-have-id  Singleton resources must not have a user-provided or system-generated ID. http://go/ipa/113  paths./api/atlas/v2/groups/{groupId}/clusters/{clusterName}/outageSimulation
warning  xgen-IPA-113-singleton-must-not-have-id  Singleton resources must not …
```
> CLOUDP-287250: Add rule IPA-113 Singleton must not have ID

- .github/scripts/create_jira_ticket.sh
- .github/workflows/api-versions-reminder.yml
_Jira ticket:_ CLOUDP-292660
I tested in a fork: https://github.com/andreaangiolillo/openapi-test/actions/runs/12676885001
Jira ticket created: https://jira.mongodb.org/browse/CLOUDP-293642 
Slack message: (The last message in the chat is the correct one 😆 )
> CLOUDP-292660: Update `api-versions-reminder.yml` to send a slack reminder and create jira ticket when APIs are approaching sunset 

- .github/workflows/optional-spec-validations.yml
- tools/postman/README.md
- tools/postman/scripts/convert-to-collection.sh
We've been seeing some failures with the postman validations in the GH actions due to network error. This PR updates the workflow to use `actions/setup-node`, which supports npm cache, to reduce these issues in the future. Currently the same approach is used for the other spectral validation workflows.
_Jira ticket:_ [CLOUDP-293820](https://jira.mongodb.org/browse/CLOUDP-293820)
> CLOUDP-293820: Update optional validations workflow to use cached npm

- tools/cli/Makefile
- tools/cli/internal/apiversion/version.go
- tools/cli/internal/apiversion/version_test.go
- tools/cli/internal/openapi/filter/extension.go
- tools/cli/internal/openapi/filter/versioning.go
- tools/cli/internal/openapi/filter/versioning_test.go
`FindLatestContentVersionMatched` never errors, removing from returned values
> chore: FindLatestContentVersionMatched never errors

- .gitignore
- package.json
- tools/spectral/ipa/metrics/config.js
- tools/spectral/ipa/metrics/metricCollection.js
- tools/spectral/ipa/metrics/utils.js
_Jira ticket:_ [CLOUDP-294461](https://jira.mongodb.org/browse/CLOUDP-294461)
`metricCollectionJob` implements the workflow for metric collection:
1. Run the Spectral command with IPA ruleset
2. Load OpenAPI file
3. Extract team ownership
4. Get rule severities
5. Load Collector results
6. Merge all the results into the `metric-collection-results.json`
`metricCollectionJob` allows custom OAS files, but the default is the `v2.json`
Example:` node metricCollection.js <path-to-OAS-file>`
`metricCollectionJob` produces a couple of output files:
- ` /outputs/metric-collection-results.json` : The data collected for metrics
- `/outputs/spectral-output.txt`: Output of spectral command
- `/outputs/spectral-report.xml`: Report for the errors
- ` ipa-collector-results-combined.log`: This file is …
> CLOUDP-294461: [Product Metrics/Observability] Implement Metric Collection workflow

- .github/workflows/optional-spec-validations.yml
Adds IPA validation to run on `optional-spec-validations` workflow. Creates an issue if the validation fails, similarly to the Postman validation.
_Jira ticket:_ [CLOUDP-294708](https://jira.mongodb.org/browse/CLOUDP-294708)
> CLOUDP-294708: Add IPA validation to optional spec validations workflow

- .github/workflows/code-health-tools.yml
- .github/workflows/optional-spec-validations.yml
Fixes IPA validation failure on the optional spec validation run, due to spectral command not found.
_Jira ticket:_ [CLOUDP-295191](https://jira.mongodb.org/browse/CLOUDP-295191)
> CLOUDP-295191: Fix optional spec validation - IPA validation

- package-lock.json
- package.json
- tools/spectral/ipa/metrics/dataDump.js
_Jira ticket:_ [CLOUDP-290414](https://jira.mongodb.org/browse/CLOUDP-290414)
This PR implements the data dump of the provided or default metric collection results file to S3 with given env variables.
The env variables will be provided by the GitHub Actions file, however, the script also allows a local .env file for local testing purposes if there are no env variables defined before code execution.
First data dump is made by running `dataDump.js` file with `.env` file filled with credentials
Differences from the ticket description:
- The code dumps the data in JSON format (not Parquet format) for testing purposes. It will be decided with DPE if Parquet format is needed
- The code dumps the full data for now. It will be decided with DPE how we can proceed with the incremental data …
> CLOUDP-290414: [Product Metrics/Observability] Set up Data Warehouse connection for exporting metrics

- package-lock.json
- package.json
- tools/spectral/ipa/metrics/dataDump.js
Updating `dataDump.js` to use parquet instead of json for the exported data (ends up being about 1/3 of the file size 🎉)
Testing:
- Pushed to staging S3 from running locally
_Jira ticket:_ [CLOUDP-295790](https://jira.mongodb.org/browse/CLOUDP-295790)
> CLOUDP-295790: Export IPA product metrics as parquet

- .github/workflows/release-IPA-metrics.yml
- tools/spectral/ipa/metrics/scripts/getShouldRunMetricsRelease.js
Adding workflow to release IPA metrics to s3.
- Uses staging creds and s3 bucket for now
- Not included in release spec workflow, this workflow will be triggered manually to verify it works as expected
Follow up:
- Add workflow to `release-spec.yml` run when we're confident it works as expected
- Update `failure-handler.yml` to also consider ipa release run result status
- Later on: When stable update to push to production s3 instead
_Jira ticket:_ [CLOUDP-290416](https://jira.mongodb.org/browse/CLOUDP-290416)
> CLOUDP-290416: Add workflow for releasing IPA metrics

- .github/workflows/release-IPA-metrics.yml
- tools/spectral/ipa/metrics/metricS3Upload.js
- tools/spectral/ipa/metrics/scripts/dataDump.js
- tools/spectral/ipa/metrics/scripts/getShouldRunMetricsRelease.js
- tools/spectral/ipa/metrics/scripts/runMetricCollection.js
- tools/spectral/ipa/metrics/utils/dataDumpUtils.js
Did some fixes of the IPA release workflow, added some extra error handling and logging for easier troubleshooting, and some refactoring, including splitting `release-IPA-metrics.yml` into two jobs, one for checking if the release should run, and the second for doing the release (skipped depending on the first step).
Tested the run manually on this branch, and it's passing: https://github.com/mongodb/openapi/actions/runs/12934985049
- Include workflow in OAS release workflow
- Pass secrets and vars from OAS release workflow to `release-IPA-metrics.yml`
- Download foas and use in `release-IPA-metrics.yml` instead of local v2.json
Later on, when we confirmed that it works as expected with the OAS release workflow, we'll change to start using the prod S3 bucket.
_Jira ticket:_ …
> CLOUDP-290416: Fix and refactor IPA metrics release workflow

- .github/workflows/release-IPA-metrics.yml
- .github/workflows/release-spec-runner.yml
- .github/workflows/release-spec.yml
- Include workflow in OAS release workflow
- Pass secrets and vars from OAS release workflow to `release-IPA-metrics.yml`
- Download FOAS and use in `release-IPA-metrics.yml` instead of local `v2.json`
- Include IPA release workflow in `failure-handler.yml`
_Jira ticket:_ [CLOUDP-296431](https://jira.mongodb.org/browse/CLOUDP-296431)
Will follow up and update to prod credentials and bucket in this ticket: [CLOUDP-296432](https://jira.mongodb.org/browse/CLOUDP-296432)
> CLOUDP-296431: Add IPA metrics release to OAS release workflow

- .github/workflows/release-IPA-metrics.yml
Adds some comments describing the IPA release workflow and what it does. Addresses comments in [previous PR](https://github.com/mongodb/openapi/pull/386)
_Jira ticket:_ [CLOUDP-296909](https://jira.mongodb.org/browse/CLOUDP-296909)
> CLOUDP-296909: Add some comments to the IPA release workflow

- .gitignore
- package-lock.json
- package.json
- tools/spectral/ipa/metrics/config.js
- tools/spectral/ipa/metrics/metricS3Upload.js
- tools/spectral/ipa/metrics/scripts/runMetricCollection.js
The parquet file previously created in IPA metrics collection wasn't a valid parquet file, but an arrow file. This PR adds [parquet-wasm](https://github.com/kylebarron/parquet-wasm) which can coverts an arrow table in memory to parquet which is then written to file. The file is compressed with gzip.
Tested locally and confirmed the created parquet and the dumped parquet in s3 are readable as parquet.
_Jira ticket:_ [CLOUDP-297242](https://jira.mongodb.org/browse/CLOUDP-297242)
> CLOUDP-297242: Fix parquet file creation for IPA metrics

- .github/workflows/api-versions-reminder.yml
Ticket: CLOUDP-297926
This PR updates this GH action to send sunset reminders to a shared slack channel and to include the apix on call in the message.
Tested in slack staging:
> CLOUDP-297926: Update GH action to send reminder about sunset to the shared slack channel

- .github/workflows/release-IPA-metrics.yml
_Jira ticket:_ CLOUDP-298521
The issue arises from performing two checkouts in the workflow. When a second checkout is executed, it resets the current workspace, causing the previously checked-out files to be lost. To address this:
1. First, checkout the dev branch and upload the OAS file as an artifact.
2. Then, perform the second checkout to the main branch and download the artifact (OAS file) to continue working with it.
> CLOUDP-298521: Decouple IPA Metrics Collection Job from FOAS Release GH Workflow (fixes)

- tools/postman/Makefile
- tools/postman/scripts/transform-postman.cjs
CLOUDP-29823
With current bash based transformation it is hard to make any changes and effectively test them.
This PR introduces transformation engine in JS (as alternative to bash/regexp patterns).
I have tested input of both jobs and they produce exactly the same output. 
Tests will be added in follow-up PR
- Easier to make follow up changes and maintain the code.
- Unit tests possible
- Runtime on my machine changed from 61 seconds to 2 seconds. 
- Removed couple immediate files/hacks
- Add tests 
- Swap and Test CI/CD system to use JS targets. 
- Add new postman transformations to introduce service accounts and document PAK enablement
> CLOUDP-298233: postman transformation in js

- tools/cli/internal/apiversion/version.go
- tools/cli/internal/apiversion/version_test.go
- tools/cli/internal/cli/versions/versions.go
_Jira ticket:_ CLOUDP-297221
- Allows the split command to handle preview, using exact match only, which means only the preview endpoints will get added to the preview spec
- Moves stability level checks into apiversion library, also making it use case insensitive
> CLOUDP-297221: Add preview support to split command

- tools/cli/internal/apiversion/version.go
- tools/cli/internal/openapi/versions.go
- tools/cli/internal/openapi/versions_test.go
- tools/cli/test/data/base_spec_with_preview.json
_Jira ticket:_ [CLOUDP-297221](https://jira.mongodb.org/browse/CLOUDP-297221)
> CLOUDP-297221: Support private preview version customization

- .github/workflows/api-versions-reminder.yml
_Jira ticket:_ CLOUDP-299199
This PR updates the notification action to stop creating Jira ticket when a new API version is about to be released.
> CLOUDP-299199: Stop creating a ticket for the new api version release

- .github/scripts/create_jira_ticket.sh
- .github/workflows/api-versions-reminder.yml
_Jira ticket:_ CLOUDP-298469
Bug: the action was creating a new Jira ticket when the JIRA API to find similar ticket returned an error.
This PR updates the logic to: 
- avoid creating a new JIRA ticket in the event of error from the Jira API call that search for similar Jira ticket
- Update the title of the ticket. During my local testing, I discovered that the JIRA API returns an error if using `[API Platform]` in the title. Removing this prefix makes the JIRA API happy again.
> CLOUDP-298469: Fix notificaiton GH aciton to not create a ticket in the event of error

- .github/scripts/create_jira_ticket.sh
- .github/workflows/failure-handler.yml
- .github/workflows/release-IPA-metrics.yml
- .github/workflows/release-cli.yml
- .github/workflows/release-spec.yml
- Passing Jira team ID to failure handler to enable setting different teams depending on what failed
- Added variables for IDs to the repo
- APIx 1 used for IPA release, APIx 2 used for OAS and CLI release
_Jira ticket:_ [CLOUDP-300586](https://jira.mongodb.org/browse/CLOUDP-300586)
> CLOUDP-300586: Add team vars to failure handler

- tools/cli/internal/apiversion/stabilitylevel.go
- tools/cli/internal/apiversion/version.go
- tools/cli/internal/cli/usage/usage.go
- tools/cli/internal/cli/versions/versions.go
- tools/cli/internal/cli/versions/versions_test.go
> CLOUDP-301830: Separate private and public preview stability levels in version command for granularity

- .github/scripts/generate_changelog.sh
This PR fixes the [error](https://github.com/mongodb/openapi/actions/runs/13453516296/job/37592561455#step:10:14) in the changelog release process:
```
Step 1: Preparing revision folder....
Generating revision metadata file
Error: invalid version date: parsing time "preview" as "2006-01-02": cannot parse "preview" as "2006". Make sure to use the format YYYY-MM-DD
Error: Process completed with exit code 1.
```
> fix: update changelog release process to avoid using preview version

- .github/scripts/split_spec.sh
- tools/cli/versions.json
_Jira ticket:_ [CLOUDP-301107](https://jira.mongodb.org/browse/CLOUDP-301107)
This PR updates the private preview release logic to generate the version.json file and move the private preview specs under v2/private
> CLOUDP-301107: move the private preview folder under v2 and generate the version.json for private preview APIs

- tools/postman/scripts/transform-for-api.sh
- tools/postman/scripts/upload-collection.sh
_Jira ticket:_ CLOUDP-288870
The script is changed as:
- The new collection name will start with ⭐️
- If the collection is created in the workspace first time, it will check if a collection with a star icon already exists. If so, it will modify the name removing the star icon
I've run the commands against an empty workspace, and it created the collection with the star in the name.
> CLOUDP-288870: Add a ⭐️ to the most recent version of the Admin API Postman collection

- tools/cli/internal/cli/split/split.go
- tools/cli/internal/cli/split/split_test.go
> CLOUDP-225860: Add support for sha in split command

- .github/workflows/code-health-tools.yml
- package-lock.json
- package.json
- tools/spectral/ipa/metrics/metricCollection.js
- tools/spectral/ipa/metrics/utils/metricCollectionUtils.js
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/scripts/generateRulesetReadme.js
- tools/spectral/ipa/utils.js
Adds a script to generate a README file in `tools/spectral/ipa/rulesets`. The file shows tables of all available rules (based on the `ipa-spectral.yaml` ruleset), and can be automatically updated when a new rule is added to the IPA validation by running:
```
npm run gen-ipa-docs
```
Also, a test is added to fail if the file is not updated, it looks like this when failed:
_Jira ticket:_ [CLOUDP-301224](https://jira.mongodb.org/browse/CLOUDP-301224)
> CLOUDP-301224: Generate README with IPA rules

- .github/workflows/api-versions-reminder.yml
GH action is failing https://github.com/mongodb/openapi/actions/runs/13627045581/job/38086419558#step:6:170 with the error:
```log
.github/scripts/create_jira_ticket.sh: line 79: JIRA_TEAM_ID: parameter null or not set
```
> fix: add JIRA_TEAM_ID to Send a Slack Notification for APIs importantevents

- tools/spectral/ipa/__tests__/createMethodRequestBodyIsRequestSuffixedObject.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/createMethodRequestBodyIsRequestSuffixedObject.js
_Jira ticket:_ CLOUDP-304055
The Create method request body should be a Request suffixed object
**Assumptions**:
- Create method is defined by POST method for REST APIs. This rule validates against the POST method requests
- Multiple media types (versions) for `requestBody` content can exist. API producers can define exceptions for each of them, adding Java`ExtensionProperty` at `@Content` level
- The schema of content should refer to a predefined Request-suffixed schema. If the schema is defined inline, it is against the guideline
> CLOUDP-304055: IPA-106 Create: The request should be a Request suffixed object

- tools/spectral/ipa/__tests__/createMethodRequestBodyIsRequestSuffixedObject.test.js
- tools/spectral/ipa/rulesets/functions/createMethodRequestBodyIsRequestSuffixedObject.js
_Jira ticket:_ CLOUDP-304055
Quick fix to include array schema cases as well
> IPA-106 Create: The request should be a Request suffixed object (fix for array schema)

- .github/scripts/split_spec.sh
- tools/cli/internal/cli/merge/merge.go
- tools/cli/internal/cli/merge/merge_test.go
- tools/cli/internal/cli/split/split.go
- tools/cli/internal/cli/split/split_test.go
- tools/cli/internal/cli/usage/usage.go
- tools/cli/internal/openapi/file.go
- tools/cli/internal/openapi/file_test.go
- tools/cli/test/e2e/cli/split_test.go
_Jira ticket:_ [CLOUDP-304430](https://jira.mongodb.org/browse/CLOUDP-304430)
> CLOUDP-304430: allow multiple formats

- tools/spectral/ipa/rulesets/IPA-005.yaml
- tools/spectral/ipa/rulesets/IPA-102.yaml
- tools/spectral/ipa/rulesets/IPA-109.yaml
- tools/spectral/ipa/rulesets/IPA-123.yaml
- tools/spectral/ipa/rulesets/README.md
_Jira ticket:_ CLOUDP-304433
This PR changes severity levels from warn to error for the IPA Spectral rules:
xgen-IPA-005-exception-extension-format
xgen-IPA-102-path-alternate-resource-name-path-param
xgen-IPA-109-custom-method-must-be-GET-or-POST
xgen-IPA-109-custom-method-must-use-camel-case
xgen-IPA-123-enum-values-must-be-upper-snake-case
> CLOUDP-304433: Initial Rollout for IPA validations

- tools/spectral/ipa/rulesets/functions/utils/collectionUtils.js
Minor driveby to clarify json paths API usage
> task: minor fix for collection utils

- tools/spectral/ipa/__tests__/createMethodShouldNotHaveQueryParameters.test.js
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/createMethodShouldNotHaveQueryParameters.js
_Jira ticket:_ CLOUDP-271994
Verify that the parameters (inline or referenced schemas) of POST operation does not have "in":"query"
> CLOUDP-271994: IPA-106: Validate Create methods accepts no query params

- tools/cli/internal/openapi/filter/README.md
- tools/cli/internal/openapi/filter/extension.go
- tools/cli/internal/openapi/filter/extension_test.go
- tools/cli/internal/openapi/filter/filter.go
- tools/cli/internal/openapi/filter/hidden_envs.go
- tools/cli/internal/openapi/filter/versioning_extension.go
- tools/cli/internal/openapi/filter/versioning_extension_test.go
_Jira ticket:_ CLOUDP-302671
Decoupling the filters related to cleaning up the spec and versioning so that we can later perform separate filtering.
> chore: decouple extension filters from versioning extension filters

- .github/workflows/release-spec.yml
- .github/workflows/retry-handler.yml
_Jira ticket:_ CLOUDP-304706
This pull request introduces a retry mechanism for handling failures in the release workflow. The most important changes include adding a new job to retry the release process and updating the failure handler to account for this new retry mechanism.
Retry mechanism for release workflow:
* [`.github/workflows/release-spec.yml`](diffhunk://#diff-aea44faec3c0b85ba535263f9b540a317c4ab32d8a8c221871a5b231fc4468b1R187-R200): Added a new `retry-handler` job that attempts to rerun the release workflow up to three times if it fails. Updated the `failure-handler` job to depend on the `retry-handler` and only run if the `retry-handler` is skipped.
* [`.github/workflows/retry-handler.yml`](diffhunk://#diff-38ee054d4979e7cd4ab591947f935ea13e8686c8a337a6ec4bbb6015cd7d7280R1-R2 …
> CLOUDP-304706: add a retry step to the FOAS release process

- tools/spectral/ipa/__tests__/createMethodShouldNotHaveQueryParameters.test.js
- tools/spectral/ipa/rulesets/functions/createMethodShouldNotHaveQueryParameters.js
_Jira ticket:_ CLOUDP-271994
Ignore `envelope` and `pretty` query params because they are about response object formatting, and they are widely used in the MMS OpenAPI spec
> CLOUDP-271994: IPA-106: Validate Create methods accepts no query params (ignore envelope and pretty query params)

- tools/spectral/ipa/__tests__/getMethodHasNoRequestBody.test.js
- tools/spectral/ipa/rulesets/IPA-104.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/getMethodHasNoRequestBody.js
Adds rule get must not have request body. Added tests and ran the validation (no offenders currently).
_Jira ticket:_ [CLOUDP-302985](https://jira.mongodb.org/browse/CLOUDP-302985)
> CLOUDP-302985: Add rule xgen-IPA-104-get-method-no-request-body

- tools/spectral/ipa/__tests__/deleteMethodResponseShouldNotHaveSchema.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-108.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/deleteMethodResponseShouldNotHaveSchema.js
- tools/spectral/ipa/rulesets/functions/utils/collectionUtils.js
CLOUDP-271997
This first PR implements OpenAPI specification validation for IPA-108 guidelines related to DELETE operations. The implementation adds linting rules that verify DELETE methods follow REST API best practices.
Rule: xgen-IPA-108-delete-response-should-be-empty
- Validates that DELETE operations return empty responses (204 No Content)
- Ensures response objects don't include schema definitions
- Implemented in deleteMethodResponseShouldNotHaveSchema.js
>  CLOUDP-271997: IPA 108 - delete method schema

- .husky/pre-commit
- .lintstagedrc.json
- CONTRIBUTING.md
- package-lock.json
- package.json
No more failed tests and missing formatting changes on your PR.
**SLO for running commands is bellow 1s.**
Adding commit hook that runs only when JS files are changed
We can add the same for golang in follow up easing load on our CI/CD system and github fair usage policies. 
Husky adds the automatic hook 
All is optional and configured by running
`npm run precommit`
Documentation provided as part of the contributing.md (introduced one as we going to add more details for IPA work going forward)
> task: add optional commit hook

- tools/spectral/ipa/__tests__/collectionIdentifierPattern.test.js
- tools/spectral/ipa/rulesets/IPA-102.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/collectionIdentifierPattern.js
This PR implements two rules from the IPA-102 specification to enforce proper resource identifier formatting in API paths:
Ensures resource identifiers begin with a lowercase letter
Only allows ASCII letters and numbers in resource identifiers
Validates against the pattern /^[a-z][a-zA-Z0-9]*$/
Collection Identifier camelCase Rule (xgen-IPA-102-collection-identifier-camelCase):
The implementation includes comprehensive unit tests that cover valid patterns, invalid patterns, and exception handling scenarios.
Edit: moved other implementation to separate PR
> CLOUDP-304930: IPA-102 pattern test

- tools/spectral/ipa/__tests__/createMethodShouldNotHaveQueryParameters.test.js
- tools/spectral/ipa/rulesets/IPA-104.yaml
- tools/spectral/ipa/rulesets/functions/createMethodRequestBodyIsRequestSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/createMethodShouldNotHaveQueryParameters.js
- tools/spectral/ipa/rulesets/functions/deleteMethod204Response.js
- tools/spectral/ipa/rulesets/functions/deleteMethodResponseShouldNotHaveSchema.js
- tools/spectral/ipa/rulesets/functions/eachCustomMethodMustBeGetOrPost.js
- tools/spectral/ipa/rulesets/functions/eachCustomMethodMustUseCamelCase.js
- tools/spectral/ipa/rulesets/functions/eachEnumValueMustBeUpperSnakeCase.js
- tools/spectral/ipa/rulesets/functions/eachPathAlternatesBetweenResourceNameAndPathParam.js
- tools/spectral/ipa/rulesets/functions/eachResourceHasGetMethod.js
- tools/spectral/ipa/rulesets/functions/exceptionExtensionFormat.js
- tools/spectral/ipa/rulesets/functions/getMethodReturnsResponseSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/getMethodReturnsSingleResource.js
- tools/spectral/ipa/rulesets/functions/getResponseCodeShouldBe200OK.js
- tools/spectral/ipa/rulesets/functions/singletonHasNoId.js
- tools/spectral/ipa/rulesets/functions/utils/schemaUtils.js
_Jira ticket:_ CLOUDP-305172
Refactored all the rule implementations according to this [pseudocode](https://docs.google.com/document/d/1sMwvhyzUaAa8Y56WXHHj44MVoEaedLsQh45K0ZwnKE4/edit?tab=t.ptrwft2w5x35#bookmark=id.ytlxpustepw7)
Left `deleteMethodNoRequestBody` and `deleteMethod404Response` because their logic is so simple. Let me know if you have concerns
> CLOUDP-305172: Refactor the rule implementations

- tools/spectral/ipa/__tests__/listResponseCodeShouldBe200OK.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-105.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/listResponseCodeShouldBe200OK.js
Adding new rule `'xgen-IPA-105-list-method-response-code-is-200` and tests. No offenders.
_Jira ticket:_ [CLOUDP-271992](https://jira.mongodb.org/browse/CLOUDP-271992)
> CLOUDP-271992: Add rule xgen-IPA-105-list-method-response-code-is-200

- tools/spectral/ipa/__tests__/getMethodReturnsResponseSuffixedObject.test.js
- tools/spectral/ipa/rulesets/functions/deleteMethod204Response.js
- tools/spectral/ipa/rulesets/functions/getMethodResponseHasNoInputFields.js
- tools/spectral/ipa/rulesets/functions/getMethodReturnsResponseSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/getMethodReturnsSingleResource.js
Optional validations failed in OAS release due to bug in rule `xgen-IPA-104-get-method-returns-response-suffixed-object`. When resolving a schema for non-2xx responses, it's undefined and wasn't checked for before checking if it has a schema.
Also added a test that will catch this if it happens again.
See failures: https://github.com/mongodb/openapi/actions/runs/13786521109
_Jira ticket:_ [CLOUDP-305831](https://jira.mongodb.org/browse/CLOUDP-305831)
> CLOUDP-305831: Fix IPA validation failed on OAS release

- .github/scripts/split_spec.sh
Fixing error
```shell
mv: cannot move 'openapi-foas.json' to './openapi/.raw/v2.json': No such file or directory
```
> fix: create folder if it does not exist

- .github/workflows/spectral-lint.yml
- package.json
IPA validation needs to run during PR process to verify if:
- IPA rule were not made error by mistake and covers existing API
- package bump does not break spectral ruleset
PR should be never merged with failed spectral validation as it will affect and break downstream builds.
Run echo "Ensuring no error violations available in OpenAPI"
Ensuring no error violations available in OpenAPI
> ipa-validation
> spectral lint ./openapi/v2.yaml --ruleset=./tools/spectral/ipa/ipa-spectral.yaml
No results with a severity of 'error' found!
> spectral-validation
> spectral lint ./openapi/v2.yaml --ruleset=./tools/spectral/.spectral.yaml
No results with a severity of 'error' found!
> task: add ipa validation to run during CI/CD process

- tools/spectral/ipa/__tests__/createMethodRequestBodyIsRequestSuffixedObject.test.js
- tools/spectral/ipa/__tests__/createMethodShouldNotHaveQueryParameters.test.js
- tools/spectral/ipa/rulesets/functions/createMethodRequestBodyIsGetResponse.js
- tools/spectral/ipa/rulesets/functions/createMethodRequestBodyIsRequestSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/createMethodShouldNotHaveQueryParameters.js
Spectral custom rule functions regarding Custom methods are updated to skip if the URI does not belong to a resource collection identifier
> Fix: Create method checks should apply resource collection URIs

- .github/scripts/branded_preview.sh
_Jira ticket:_ CLOUDP-305844
[Branded preview](https://htmlpreview.github.io/?https://github.com/mongodb/openapi/blob/dev/openapi/branded-preview.html) list v2.json and v2.yaml specs and the preview does not work for private preview specs.
This PR updates the branded_preview.sh logic to remove the v2.json|yaml files and to use the correct path for private preview specs
> CLOUDP-305844: fix branded_preview to avoid listing v2.json/v2.yaml files

- tools/spectral/ipa/__tests__/createMethodRequestHasNoReadonlyFields.test.js
- tools/spectral/ipa/rulesets/functions/createMethodRequestHasNoReadonlyFields.js
_Jira ticket:_ CLOUDP-304939
Include resource collection URI check for `xgen-IPA-106-create-method-request-has-no-readonly-fields` rule
> CLOUDP-304939: IPA 106: Create : A Request object must include only input fields (consider resource collection URIs only)

- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/README.md
Includes "This rule applies only to POST requests targeting resource collection URIs." sentence to the IPA-106:Create rules
> Fix: Refine Create method descriptions with the resource collection applicability

- tools/spectral/ipa/__tests__/utils/resourceEvaluation.test.js
- tools/spectral/ipa/rulesets/functions/utils/resourceEvaluation.js
_Jira ticket:_ CLOUDP-306161
Update `isSingleResourceIdentifier` function to check if the URI is
`Single resource path` = `resourceCollectionPath` + `/{resourceId}`
All the rules regarding IPA-104:Get are affected. Following the PR merge, I will check if there are changes in exceptions defined in MMS
> CLOUDP-306161: Improve single resource path evaluation

- package.json
- tools/spectral/ipa/scripts/filter-ipa-violations.js
Simple helper that generates markdown file with violations per specific rule. 
This allows you to detect violations  per new tyle and apply them easily.
Example:
```
npm run ipa-filter xgen-IPA-102-collection-identifier-camelCase
```
Using this myself. We can merge if we see value.
> task: filter violations to add to the report

- tools/spectral/ipa/__tests__/createMethodRequestBodyIsGetResponse.test.js
- tools/spectral/ipa/__tests__/createMethodRequestBodyIsRequestSuffixedObject.test.js
- tools/spectral/ipa/__tests__/createMethodRequestHasNoReadonlyFields.test.js
- tools/spectral/ipa/__tests__/createMethodResponseCodeIs201Created.test.js
- tools/spectral/ipa/__tests__/createMethodShouldNotHaveQueryParameters.test.js
- tools/spectral/ipa/__tests__/utils/compareUtils.test.js
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/createMethodRequestBodyIsGetResponse.js
- tools/spectral/ipa/rulesets/functions/utils/compareUtils.js
_Jira ticket:_ CLOUDP-304053
Refines the rule with the latest spec [changes](https://docs.google.com/document/d/1sMwvhyzUaAa8Y56WXHHj44MVoEaedLsQh45K0ZwnKE4/edit?tab=t.ptrwft2w5x35#bookmark=id.s543xrkvig2k)
Before comparing the schemas:
- Remove readOnly:true properties from Get response
- Remove writeOnly:true properties from Create request
Drive-by changes on the descriptions and error messages to follow the latest documentation format
> CLOUDP-304053: IPA-106:Create - The resource must be the request body (exclude readOnly:true and writeOnly:true)

- tools/spectral/ipa/__tests__/utils/compareUtils.test.js
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA106CreateMethodRequestBodyIsGetResponse.js
- tools/spectral/ipa/rulesets/functions/utils/compareUtils.js
_Jira ticket:_ CLOUDP-304053
Refinements:
- If the Get response and Create Request both references a schema and if their names are equal, it means that they are equal and no need to proceed with deep equality check.
- If one of them or two of them does not reference to a schema, deep equality check will be made
- Before deep equality check, title, description and required fields will be removed
- Deep equality check:
-- Properties will be compared based on their names and types
-- Resolved oneOf, allOf, anyOf, and discriminator field values are expected to be completely same
> CLOUDP-304053: IPA-106:Create - The resource must be the request body (Refinement)

- .github/workflows/api-versions-reminder.yml
CLOUDP-306812
_Jira ticket:_ CLOUDP-306812
The Sunset Reminder action is using the OpenAPI spec file (openapi/v2.json), which was recently updated to remove all x-gen extensions (see PR [#497](https://github.com/mongodb/openapi/pull/497)). As a result of this change, the action could no longer retrieve the x-xgen-owner-team extension, leading to a different SHA value compared to the one generated the week before.
This PR updates the action to use the .raw/v2.json file which contains all the extensions
> CLOUDP-306812: update gh action to use new raw spec

- tools/spectral/ipa/scripts/filter-ipa-violations.js
For exception management I have been manually copying downstream PR's openAPI so far. This PR automates it so you can automatically refresh exceptions based on new openapi changes.
Example:
```
npm run ipa-filter-violations xgen-IPA-102-collection-identifier-camelCase https://raw.githubusercontent.com/mongodb/openapi/refs/heads/dev/openapi/.raw/v2.yaml
```
Example for fixed issues (verification of exception PR):
```
npm run ipa-filter-violations xgen-IPA-108-delete-response-should-be-empty https://raw.githubusercontent.com/mongodb/openapi/refs/heads/dev/openapi/.raw/v2.yaml 
> ipa-filter-violations
> node tools/spectral/ipa/scripts/filter-ipa-violations.js xgen-IPA-108-delete-response-should-be-empty https://raw.githubusercontent.com/mongodb/openapi/refs/heads/dev/openapi/.raw/v2.yaml …
```
> fix: allow to use custom openapi file

- tools/spectral/ipa/rulesets/IPA-104.yaml
- tools/spectral/ipa/rulesets/IPA-105.yaml
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/IPA-108.yaml
- tools/spectral/ipa/rulesets/IPA-109.yaml
- tools/spectral/ipa/rulesets/IPA-113.yaml
- tools/spectral/ipa/rulesets/IPA-123.yaml
- tools/spectral/ipa/rulesets/README.md
Adding technical specifications for the each rule we have in main.
Pefered way to review -> read README.md file for all the rules
> CLOUDP-305862 - Add missing rule Technical Specifications

- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/scripts/generateRulesetReadme.js
Initially IPA have been single rule now we have multiple rules per IPA so we need plural form in docs.
> CLOUDP-305862: change plural form in docs

- .github/workflows/code-health-foascli.yml
- .github/workflows/code-health-tools.yml
This pull request includes changes to the GitHub Actions workflows to improve the code health checks for different tools. The most significant changes involve creating a new workflow for the CLI tool and updating the existing workflow for other tools.
* Added a new workflow file `.github/workflows/code-health-foascli.yml` to handle code health checks specifically for the CLI tool, including build, unit tests, lint, and end-to-end tests.
* Modified the `.github/workflows/code-health-tools.yml` file to narrow the scope to only `tools/postman` and `tools/spectral` directories, and removed CLI-specific jobs from this workflow. [[1]](diffhunk://#diff-b2f6e857d1e8357cfffb4a0389831809a40aeb2bb404959caa74e4f2f75a4d75L7-L48) [[2]](diffhunk://#diff-b2f6e857d1e8357cfffb4a0389831809a40aeb2bb404959caa7 …
> chore: separate code health gh action per tools to run only when specific paths are changed

- tools/spectral/ipa/__tests__/IPA107UpdateMethodResponseIsGetMethodResponse.test.js
- tools/spectral/ipa/rulesets/IPA-107.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA107UpdateMethodResponseIsGetMethodResponse.js
- tools/spectral/ipa/rulesets/functions/utils/methodUtils.js
Adds rule `xgen-IPA-107-update-method-response-is-get-method-response` and tests. Also drive-by to correct the test for `IPA106CreateMethodResponseIsGetMethodResponse.test.js` where there were request bodies validated instead of response contents.
_Jira ticket:_ [CLOUDP-304945](https://jira.mongodb.org/browse/CLOUDP-304945)
One violation currently. Will do combined follow-up PR to add exceptions for multiple "update method" related IPAs.
> CLOUDP-304945: Add xgen-IPA-107-update-method-response-is-get-method-response

- tools/spectral/ipa/__tests__/IPA108DeleteMethod204Response.test.js
- tools/spectral/ipa/__tests__/IPA108DeleteMethod404Response.test.js
- tools/spectral/ipa/__tests__/IPA108DeleteMethodNoRequestBody.test.js
- tools/spectral/ipa/__tests__/IPA108DeleteMethodResponseShouldNotHaveSchema.test.js
- tools/spectral/ipa/rulesets/IPA-108.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA108DeleteMethod204Response.js
- tools/spectral/ipa/rulesets/functions/IPA108DeleteMethod404Response.js
- tools/spectral/ipa/rulesets/functions/IPA108DeleteMethodNoRequestBody.js
- tools/spectral/ipa/rulesets/functions/IPA108DeleteMethodResponseShouldNotHaveSchema.js
Refined DELETE operations validation rules (IPA-108) to only apply to single resource endpoints with path parameters. This ensures proper REST semantics where DELETE should operate on specific resources rather than collections.
- Updated documentation to clarify rule application scope
- Added test cases to verify correct behavior for both resource and collection endpoints
- Added path parameter detection using the `isSingleResourceIdentifier` helper
Reused helper function created by @yelizhenden-mdb. Thank you for refinement and implementation!
> CLOUDP-306347: isSingleResourceIdentifier for delete operations

- openapi/v2/openapi-2025-03-12.json
- tools/cli/internal/openapi/filter/hidden_envs.go
- tools/cli/internal/openapi/filter/hidden_envs_test.go
- tools/cli/test/data/split/dev/openapi-mms.json
- tools/cli/test/data/split/dev/openapi-v2-2023-01-01.json
- tools/cli/test/data/split/dev/openapi-v2-2023-01-01.yaml
- tools/cli/test/data/split/dev/openapi-v2-2023-02-01.json
- tools/cli/test/data/split/dev/openapi-v2-2023-02-01.yaml
- tools/cli/test/data/split/dev/openapi-v2-2023-10-01.json
- tools/cli/test/data/split/dev/openapi-v2-2023-10-01.yaml
- tools/cli/test/data/split/dev/openapi-v2-2023-11-15.json
- tools/cli/test/data/split/dev/openapi-v2-2023-11-15.yaml
- tools/cli/test/data/split/dev/openapi-v2-2024-05-30.json
- tools/cli/test/data/split/dev/openapi-v2-2024-05-30.yaml
- tools/cli/test/data/split/dev/openapi-v2-2024-08-05.json
- tools/cli/test/data/split/dev/openapi-v2-2024-08-05.yaml
- tools/cli/test/data/split/dev/openapi-v2-2025-01-01.json
- tools/cli/test/data/split/dev/openapi-v2-2025-01-01.yaml
- tools/cli/test/data/split/dev/openapi-v2.json
- tools/cli/test/data/split/dev/openapi-v2.yaml
- tools/cli/test/data/split/prod/openapi-mms.json
_Jira ticket:_ CLOUDP-307054
Applied the filter into the spec: 
```shell
./bin/foascli filter --env prod -s ../../openapi/v2/openapi-2025-03-12.json -o ../../openapi/v2/openapi-2025-03-12.json --format json
```
File result:
https://github.com/mongodb/openapi/pull/560/commits/50f067615b453790acc33f0de4292c12c7bf50e2
> CLOUDP-307054: Add support for hidden-env properties and schemas

- tools/spectral/ipa/__tests__/IPA107UpdateMethodMustNotHaveQueryParams.test.js
- tools/spectral/ipa/__tests__/IPA107UpdateResponseCodeShouldBe200OK.test.js
- tools/spectral/ipa/rulesets/IPA-107.yaml
- tools/spectral/ipa/rulesets/README.md
We have two rules for Update Method that are separated per PUT and PATCH, this PR combined them into one rule. Will update affected exceptions in follow-up.
_Jira ticket:_ [CLOUDP-307110](https://jira.mongodb.org/browse/CLOUDP-307110)
> CLOUDP-307110: Combine separated put and patch IPA rules

- tools/spectral/ipa/__tests__/IPA112AvoidProjectFieldNames.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-112.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA112AvoidProjectFieldNames.js
_Jira ticket:_ CLOUDP-272001
```
Schema field names should avoid using "project", "projects", or "projectId".
Rule checks for the following conditions:
- Searches through all schemas in the API definition
- Identifies property names that match "project" (case-insensitive)
- Reports any instances where these field names are used
- Suggests using "group", "groups", or "groupId" as alternatives
```
15 violations found
> CLOUDP-272001: IPA-112: Disallow usages of project in the api

- tools/spectral/ipa/__tests__/IPA104GetMethodReturnsResponseSuffixedObject.test.js
- tools/spectral/ipa/__tests__/IPA106CreateMethodRequestBodyIsRequestSuffixedObject.test.js
- tools/spectral/ipa/__tests__/IPA107UpdateMethodRequestBodyIsUpdateRequestSuffixedObject.test.js
- tools/spectral/ipa/rulesets/IPA-107.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA104GetMethodReturnsResponseSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/IPA107UpdateMethodRequestBodyIsUpdateRequestSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/utils/validations.js
Adds rule `xgen-IPA-107-update-method-request-body-is-update-request-suffixed-object` and also refactor to use a common validation function for all suffix related rules.
_Jira ticket:_ [CLOUDP-304943](https://jira.mongodb.org/browse/CLOUDP-304943)
> CLOUDP-304943: IPA rule for Update request schema suffix

- tools/spectral/ipa/__tests__/IPA112AvoidProjectFieldNames.test.js
- tools/spectral/ipa/__tests__/utils/schemaUtils.test.js
- tools/spectral/ipa/rulesets/IPA-112.yaml
- tools/spectral/ipa/rulesets/functions/IPA112AvoidProjectFieldNames.js
- tools/spectral/ipa/rulesets/functions/utils/schemaUtils.js
_Jira ticket:_ CLOUDP-272001
Fix: Split the field name into words, assuming it follows camelCase. If any of the split words match a prohibited word, it is considered a violation.
> CLOUDP-272001: Disallow usages of project in the api (fix)

- tools/spectral/ipa/__tests__/IPA107UpdateMethodRequestBodyIsGetResponse.test.js
- tools/spectral/ipa/__tests__/IPA107UpdateMethodRequestHasNoReadonlyFields.test.js
- tools/spectral/ipa/__tests__/IPA107UpdateMethodResponseIsGetMethodResponse.test.js
- tools/spectral/ipa/rulesets/IPA-107.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA107UpdateMethodRequestBodyIsGetResponse.js
- tools/spectral/ipa/rulesets/functions/IPA107UpdateMethodRequestHasNoReadonlyFields.js
- tools/spectral/ipa/rulesets/functions/IPA107UpdateMethodResponseIsGetMethodResponse.js
Noticed some IPA 107 rules (Update method) which did not cover singleton resources. This PR updates these rules to include singleton resources and adds tests to cover this.
8 singleton resources with new violations, will add exceptions in follow-up PR.
_Jira ticket:_ [CLOUDP-307341](https://jira.mongodb.org/browse/CLOUDP-307341)
> CLOUDP-307341: Include singleton in IPA 107 rules

- tools/spectral/ipa/__tests__/IPA125OneOfMustHaveDiscriminator.test.js
- tools/spectral/ipa/__tests__/__helpers__/testRule.js
- tools/spectral/ipa/rulesets/IPA-125.yaml
- tools/spectral/ipa/rulesets/functions/IPA125OneOfMustHaveDiscriminator.js
Enforce Discriminator when oneOf is present. 
_Jira ticket:_ CLOUDP-306580
> CLOUDP-306580: IPA 125 - Each oneOf property must be accompanied with discriminator

- tools/spectral/ipa/__tests__/IPA125OneOfMustHaveDiscriminator.test.js
- tools/spectral/ipa/__tests__/IPA125OneOfNoBaseTypes.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-125.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA125OneOfMustHaveDiscriminator.js
- tools/spectral/ipa/rulesets/functions/IPA125OneOfNoBaseTypes.js
Base types oneOf validator. 
> Found 0 violations to fix
🤗 
_Jira ticket:_ CLOUDP-306580
> CLOUDP-306580: base types oneof

- tools/spectral/ipa/rulesets/IPA-125.yaml
- tools/spectral/ipa/rulesets/README.md
Modify IPA-125 rule severity levels from `error` to `warn` because they haven't been rolled out yet
Closes #580
> Fix: Degrade severity level for IPA-125 rules

- .github/workflows/spectral-lint.yml
Removes permissions from Spectral Lint workflow to keep the default permissions
Modify `file_glob` to `v2.yaml` only, because it already points to `github/workspace`
> Fix: Remove permissions from Spectral Lint workflow

- tools/spectral/ipa/__tests__/IPA113SingletonHasNoDeleteMethod.test.js
- tools/spectral/ipa/__tests__/IPA113SingletonHasUpdateMethod.test.js
- tools/spectral/ipa/rulesets/IPA-113.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA113SingletonHasNoDeleteMethod.js
- tools/spectral/ipa/rulesets/functions/IPA113SingletonHasUpdateMethod.js
- tools/spectral/ipa/rulesets/functions/utils/resourceEvaluation.js
Adds IPA 113 rules:
- `xgen-IPA-113-singleton-must-not-have-delete-method`
- `xgen-IPA-113-singleton-should-have-update-method`
**Note:** `xgen-IPA-113-singleton-must-not-have-delete-method` is covering the statement "Singleton resources must not define the Create or Delete standard methods" however I only implemented the check for DELETE since we use the absence of POST to determine if a resource is a singleton resource.
**Note:** `xgen-IPA-113-singleton-should-have-update-method` in the guidelines mentions GET as well, but this is already covered by a rule for 104, so didn't include this validation here.
- Added unit tests
- Ran validation, currently:
- 3 violations for `xgen-IPA-113-singleton-must-not-have-delete-method`
- 24 violations for …
> CLOUDP-304958: IPA rule singleton must not have delete

- tools/spectral/ipa/__tests__/IPA112AvoidProjectFieldNames.test.js
- tools/spectral/ipa/rulesets/IPA-112.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA112AvoidProjectFieldNames.js
_Jira ticket:_ CLOUDP-272001
After discussion [here](https://github.com/10gen/mms/pull/124508#discussion_r2006060661), `gcp` will be ignored for this validation. It is an ignore list to facilitate future needs.
> IPA-112: Disallow usages of project in the api (Fix: Ignore "gcp")

- tools/spectral/ipa/__tests__/IPA117HasDescription.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117HasDescription.js
Adds rule to check for descriptions presence and empty descriptions, it covers:
- Info object
- Tags
- Operation objects
- Inline schema properties for operation object requests and responses
- Parameter objects (in operations and components)
- Schema properties
It can replace the legacy spectral check we have right now.
The violations are the same as we have for the legacy rule:
```
xgen-IPA-117-description  Description not found. API producers must provide descriptions for Properties, Operations and Parameters. https://mdb.link/mongodb-atlas-openapi-validation#xgen-IPA-117-description  components.schemas.ClusterProviderSettings.properties.providerName
xgen-IPA-117-description  Description not found. API producers must provide descriptions for Properties, Operations and Parameters. …
```
> CLOUDP-304965: IPA rule for descriptions

- tools/spectral/ipa/__tests__/IPA112BooleanFieldNamesAvoidIsPrefix.test.js
- tools/spectral/ipa/rulesets/IPA-112.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA112BooleanFieldNamesAvoidIsPrefix.js
_Jira ticket:_ CLOUDP-272000
Adds `xgen-IPA-112-boolean-field-names-avoid-is-prefix` rule
47 violations are found to be exempted in the MMS code
> CLOUDP-272000: Boolean field names avoid "is" prefix

- tools/spectral/ipa/__tests__/IPA112BooleanFieldNamesAvoidIsPrefix.test.js
- tools/spectral/ipa/__tests__/IPA112FieldNamesAreCamelCase.test.js
- tools/spectral/ipa/rulesets/IPA-112.yaml
- tools/spectral/ipa/rulesets/functions/IPA112AvoidProjectFieldNames.js
- tools/spectral/ipa/rulesets/functions/IPA112BooleanFieldNamesAvoidIsPrefix.js
- tools/spectral/ipa/rulesets/functions/IPA112FieldNamesAreCamelCase.js
_Jira ticket:_ CLOUDP-271999
(and other tickets CLOUDP-272000 and CLOUDP-272001)
Fix on the IPA-112 rule implementations:
If the path to property is a resolved version of a schema reference, skip it to prevent duplicate violations. The referenced schemas will be validated separately
> Fix on IPA-112 rule implementation

- tools/spectral/ipa/rulesets/IPA-112.yaml
_Jira ticket:_ CLOUDP-271999
(affects other tickets CLOUDP-272000 and CLOUDP-272001)
Adds `resolved: false` to IPA-112 rule definitions to show the correct paths in the error messages
Example:
Before:
` 54973:27  warning  xgen-IPA-112-field-names-are-camel-case
Property "diskGB" must use camelCase format. https://mdb.link/mongodb-atlas-openapi-validation#xgen-IPA-112-field-names-are-camel-case
components.schemas.DiskGBAutoScaling`
After:
`  32773:20  warning  xgen-IPA-112-field-names-are-camel-case
Property "diskGB" must use camelCase format. https://mdb.link/mongodb-atlas-openapi-validation#xgen-IPA-112-field-names-are-camel-case 
components.schemas.AdvancedAutoScalingSettings.properties.diskGB`
> IPA-112 fix for incorrect paths in the error messages

- tools/postman/scripts/transform-for-api.sh
- tools/postman/scripts/transform-postman.js
Fix in the postman transformation to reduce size of the generated file. It reduces filesize by 50% 
Applied to both transformations. Tested by uploading file to my private postman.
In previous PR #600  I used to take approach where we removed all possible fields and seek for possible redundancies.
During the process I have logged difference and created table covering the biggest wins we can get for the size compared to the experience we loose. AI analised size redundancies and different use cases and found that we can get 50% efficiency on removing whitespaces from json. All other improvements did not had the same impact to the file so I did not included them in the process.
> CLOUDP-308303: remove whitespaces to reduce collection size

- tools/spectral/ipa/__tests__/IPA117DescriptionShouldNotUseTables.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117DescriptionShouldNotUseTables.js
Adds rule `xgen-IPA-117-description-should-not-use-inline-tables` which checks with regex if the description contains characters denoting a markdown table, specifically the separator between the table header and the rows (`|---|`, `|:---|`, `|---:|` or `|:---:|`).
It's still allowed to write for example `Value is: this | that`.
Checked the violations (currently 33) to ensure no false positives.
_Jira ticket:_ [CLOUDP-304968](https://jira.mongodb.org/browse/CLOUDP-304968)
> CLOUDP-304968: IPA rule xgen-IPA-117-description-should-not-use-inline-tables

- .github/workflows/code-health-foascli.yml
- tools/cli/.golangci.bck.yml
- tools/cli/.golangci.yml
- tools/cli/Makefile
- tools/cli/internal/breakingchanges/exemptions_test.go
- tools/cli/internal/openapi/filter/schemas_test.go
- tools/cli/internal/openapi/filter/sunset_test.go
- tools/cli/internal/openapi/oasdiff_test.go
- tools/cli/test/data/exemptions/exemptions.txt
- tools/cli/test/e2e/cli/changelog_test.go
This PR upgrade golangci-lint to v2 and fixes linting errors. I followed the migration guide: https://golangci-lint.run/product/migration-guide/
> chore: Upgrade golangci-lint to v2 

- README.md
- tools/cli/README.md
> CLOUDP-273196: update `mongodb/openapi` with readme

- tools/cli/internal/openapi/filter/sunset.go
- tools/cli/internal/openapi/filter/sunset_test.go
This pull request introduces changes to the `SunsetFilter` functionality in the `tools/cli/internal/openapi/filter` package. The main goal is to enhance the handling of the "sunset" extension within OpenAPI operations and their responses. Additionally, new test cases are added to ensure the correctness of these changes.
Enhancements to `SunsetFilter`:
* [`tools/cli/internal/openapi/filter/sunset.go`](diffhunk://#diff-4402820713197db547cf70d716c84bc59371389eb0158f53a52c06dbd93f4422R52-R57): Added logic to remove the "sunset" extension if its value is set to "sunsetToBeDecided". This check is performed both within the 20X response and as part of the operation itself. [[1]](diffhunk://#diff-4402820713197db547cf70d716c84bc59371389eb0158f53a52c06dbd93f4422R52-R57) …
> fix: update the sunset filter to remove the `9999-12-01` also from the operation extension.

- tools/spectral/ipa/__tests__/IPA117DescriptionShouldNotUseLinks.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117DescriptionShouldNotUseLinks.js
New rule `xgen-IPA-117-description-should-not-use-inline-links` checks for inline MD links in the descriptions. It does not check for HTML links since this is covered by `xgen-IPA-117-description-must-not-use-html`.
_Jira ticket:_ [CLOUDP-306571](https://jira.mongodb.org/browse/CLOUDP-306571)
> CLOUDP-306571: Add rule xgen-IPA-117-description-should-not-use-inline-links

- eslint.config.mjs
- tools/spectral/ipa/rulesets/functions/IPA105ListMethodHasNoRequestBody.js
- tools/spectral/ipa/rulesets/functions/IPA105ListMethodResponseIsGetMethodResponse.js
- tools/spectral/ipa/rulesets/functions/IPA105ListResponseCodeShouldBe200OK.js
- tools/spectral/ipa/rulesets/functions/IPA106CreateMethodResponseIsGetMethodResponse.js
- tools/spectral/ipa/rulesets/functions/IPA110CollectionsRequestHasItemsPerPageQueryParam.js
- tools/spectral/ipa/rulesets/functions/IPA110CollectionsRequestHasPageNumQueryParam.js
- tools/spectral/ipa/rulesets/functions/IPA110CollectionsResponseDefineResultsArray.js
- tools/spectral/ipa/rulesets/functions/IPA110CollectionsUsePaginatedPrefix.js
Replaces the check if a path belongs to a List method 
```
!isResourceCollectionIdentifier(resourcePath) ||
(isResourceCollectionIdentifier(resourcePath) && isSingletonResource(getResourcePathItems(resourcePath, oas.paths)))
```
with
`!isResourceCollectionIdentifier(resourcePath) || isSingletonResource(getResourcePathItems(resourcePath, oas.paths)
`
Related discussion: https://github.com/mongodb/openapi/pull/622#discussion_r2016194427
> Fix: List method checks

- README.md
- tools/cli/README.md
addressing https://github.com/mongodb/openapi/pull/618#discussion_r2014294451
> chore: addressed follow up comment

- tools/postman/scripts/upload-collection.sh
Done research and it looks like postman API gets overwhelmed sometimes over period of 1-2 minutes.
Current retry mechanism uses backoff mechanism that reattempt next request in double time of the previous one starting from 1s.
This PR extends retries to be attempted every 30 seconds and increases the amount of retries to 10. 
```
--retry 10: This sets the number of retries to 10.
--retry-delay 30: Adds a delay of 30 seconds between retry attempts. This helps increase the time between retries.
--retry-max-time 300: Specifies the maximum time for all retry operations to occur, which is set to 300 seconds (5 minutes).
```
> CLOUDP-309394 - Increase postman upload timelines

- tools/spectral/ipa/__tests__/IPA117ObjectsMustBeWellDefined.test.js
- tools/spectral/ipa/__tests__/IPA117ParameterHasExamplesOrSchema.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117ObjectsMustBeWellDefined.js
- tools/spectral/ipa/rulesets/functions/IPA117ParameterHasExamplesOrSchema.js
- tools/spectral/ipa/rulesets/functions/utils/componentUtils.js
- tools/spectral/ipa/rulesets/functions/utils/schemaUtils.js
Adds two rules to partially validate IPA 117:
> API producers must provide a well-defined schema or example(s)
- `xgen-IPA-117-parameter-has-examples-or-schema` corresponds to the legacy spectral rule
- `xgen-IPA-117-objects-must-be-well-defined` checks that components of `type: 'object'` has schema, example(s), properties, additionalProperties or oneOf/anyOf/allOf
See README additions for more details.
_Jira ticket:_ [CLOUDP-306572](https://jira.mongodb.org/browse/CLOUDP-306572)
> CLOUDP-306572: Adds rule for "well defined schema"

- tools/spectral/ipa/__tests__/IPA117PlaintextResponseMustHaveExample.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117PlaintextResponseMustHaveExample.js
Updates IPA rule `xgen-IPA-117-plaintext-response-must-have-example` to ignore file types. Added a test to cover case.
_Jira ticket:_ [CLOUDP-306573](https://jira.mongodb.org/browse/CLOUDP-306573)
> CLOUDP-306573: Dont require gzip to have example

- tools/spectral/ipa/__tests__/IPA114AuthenticatedEndpointsHaveAuthErrors.test.js
- tools/spectral/ipa/rulesets/IPA-114.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA114AuthenticatedEndpointsHaveAuthErrors.js
_Jira ticket:_ CLOUDP-304964
```
xgen-IPA-114-authenticated-endpoints-have-auth-errors:
description: |
Authenticated endpoints must define 401 and 403 responses.
This rule checks that all authenticated endpoints (those without explicit 'security: []' 
and not containing '/unauth' in the path) include 401 and 403 responses.
```
> CLOUDP-304964: IPA-114: Errors (check for 401 and 403 codes for authorized endpoints)

- tools/spectral/ipa/__tests__/IPA114ErrorResponsesReferToApiError.test.js
- tools/spectral/ipa/rulesets/IPA-114.yaml
- tools/spectral/ipa/rulesets/functions/IPA114ErrorResponsesReferToApiError.js
- tools/spectral/ipa/rulesets/functions/utils/componentUtils.js
_Jira ticket:_ CLOUDP-304960
Fixes:
- Exceptions will only be collected at the response level.
- There might be multiple errors for one response, assuming there might be several versions of responses (CLOUDP-276969)
- Add error if referenced schema is not valid
(`openapi-api-registry.json` refers to schemas in `openapi-mms.json`, which cannot be resolved in custom Spectral rule functions, therefore they will appear as errors)
- For investigating external schema reference resolution further, CLOUDP-309694 is created
> IPA-114: Errors (fix for exception level)

- tools/postman/scripts/upload-collection.sh
This PR updates the `curl` command parameters used in our Postman calls, based on the observations from our CI/CD pipeline from the last failure.
During our evaluation of last failure based on tracing we added, we discovered that postman in fact was overwhelmed and took entire 2 minutes to get error. I could not reproduce this locally :(
This resulted in only two requests being made due to the previous `--retry-max-time` limit of 300 seconds.
To enhance the robustness and reliability of our calls, we have decided to adjust the parameters as follows:
- **Retry Attempts**: Changing the `--retry` option to retry up to **7 times** to finetune between instant failures and each request taking max 2 minutes.
- **Updated Maximum Retry Time**: increased it to `--retry-max-time 1200` to allow more …
> CLOUDP-309577: Update `curl` Parameters for Improved Reliability

- tools/spectral/ipa/__tests__/IPA118NoAdditionalPropertiesFalse.test.js
- tools/spectral/ipa/__tests__/utils/compareUtils.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-118.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA118NoAdditionalPropertiesFalse.js
- tools/spectral/ipa/rulesets/functions/utils/compareUtils.js
_Jira ticket:_ CLOUDP-306575
```
xgen-IPA-118-no-additional-properties-false:
description: |
Schemas must not use `additionalProperties: false`
This rule checks that schemas don't restrict additional properties by setting `additionalProperties: false`.
Schemas without explicit `additionalProperties` settings (which default to true) or with `additionalProperties` set to `true` are compliant.
This rule checks all nested schemas, but only parent schemas can be marked for exception.
```
No violations to fix
> CLOUDP-306575: IPA-118: Extensible by Default

- tools/spectral/ipa/__tests__/IPA119NoDefaultForCloudProviders.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-119.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA119NoDefaultForCloudProviders.js
_Jira ticket:_ CLOUDP-306576
```
xgen-IPA-119-no-default-for-cloud-providers:
description: |
When using a provider field or parameter, API producers should not define a default value.
This rule checks fields and parameters named "cloudProvider" and ensures they do not have a default value.
It also checks enum fields that might contain cloud provider values.
All cloudProviderEnumValues should be listed in the enum array.
```
Found 8 violations, all of them input parameters
> CLOUDP-306576: IPA-119: Multi-Cloud Support by Default

- tools/spectral/ipa/__tests__/IPA119NoDefaultForCloudProviders.test.js
- tools/spectral/ipa/rulesets/functions/IPA119NoDefaultForCloudProviders.js
_Jira ticket:_ CLOUDP-306576
If a field or parameter isn't related to a cloud provider, don’t mark the component as adopting the rule
> CLOUDP-306576: IPA-119: Multi-Cloud Support (Fix)

- tools/spectral/ipa/__tests__/IPA121DateTimeFieldsMentionISO8601.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-121.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA121DateTimeFieldsMentionISO8601.js
_Jira ticket:_ CLOUDP-306577
```
xgen-IPA-121-date-time-fields-mention-iso-8601:
description: |
Fields with format="date-time" should mention ISO 8601 and UTC in their description.
```
Found 48 violations to fix
> CLOUDP-306577: IPA-121: Datetime

- .github/workflows/release-postman.yml
- tools/postman/collection-description.md
- tools/postman/scripts/transform-for-api.sh
- tools/postman/scripts/transform-postman.js
CLOUDP-298233
SA GA changes. Not to be merged. 
1. Moved to JS transformation (verified correctness by loading collection into postman.
2. Added missing operations post transformation
Cannot be merged before OpenAPI has Service Account listed as first item.
Post merge we should update section in existing blog post: 
https://www.mongodb.com/developer/products/atlas/admin-api-postman/
> CLOUDP-298233: Postman SA support

- tools/spectral/ipa/__tests__/IPA124ArrayMaxItems.test.js
- tools/spectral/ipa/rulesets/IPA-124.yaml
_Jira ticket:_ CLOUDP-306579
`results` is a field of `PaginatedViews` and is included in every paginated schema. Therefore, it will be ignored during checks
Violation count dropped to 359
> CLOUDP-306579: IPA-124: Repeated Fields (fix)

- tools/spectral/ipa/__tests__/IPA126TagNamesShouldUseTitleCase.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/IPA-126.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA126TagNamesShouldUseTitleCase.js
_Jira ticket:_ CLOUDP-306582
```
xgen-IPA-126-tag-names-should-use-title-case:
description: |
Tag names in the OpenAPI specification should use Title Case.
Rule checks for the following conditions:
- All tag names defined in the OpenAPI tags object should use Title Case 
- Title Case means each word starts with an uppercase letter, and the rest are lowercase
```
Found 13 violations
> CLOUDP-306582: IPA-126: Top-Level API Names

- tools/cli/internal/apiversion/version.go
- tools/cli/internal/cli/split/split_test.go
- tools/cli/internal/openapi/filter/extension.go
- tools/cli/internal/openapi/filter/hidden_envs.go
- tools/cli/internal/openapi/filter/info.go
- tools/cli/internal/openapi/filter/operations.go
- tools/cli/internal/openapi/filter/tags.go
- tools/cli/internal/openapi/filter/versioning.go
- tools/cli/internal/openapi/filter/versioning_extension.go
CLOUDP-311375
This PR updates `foascli split` to add support for `upcoming` api version.
> CLOUDP-311375: Update `foascli split` command to support `upcoming` apis

- tools/spectral/.spectral.yaml
_Jira ticket:_ CLOUDP-311390
Remove `xgen-docs-parameter-examples-or-schema` legacy Spectral rule, because the duplicate `xgen-IPA-117-parameter-has-examples-or-schema` will be rolled out
> CLOUDP-311390: Remove duplicate legacy Spectral rule

- tools/cli/internal/apiversion/version.go
- tools/cli/internal/openapi/filter/bump.go
- tools/cli/internal/openapi/filter/bump_test.go
- tools/cli/internal/openapi/filter/filter.go
- tools/cli/internal/openapi/filter/filter_test.go
CLOUDP-311381
This PR adds a new filter to `foascli split` to include custom bump.sh fields for preview and upcoming apis.
I generated the spec with my changes and tested that preview spec is correctly rendered.
https://bump.sh/andrea/doc/test-preview/operation/operation-exportchartsdashboard
> CLOUDP-311381: Add a new filter to foascli to support bump.sh fields

- tools/spectral/ipa/__tests__/__helpers__/testRule.js
- tools/spectral/ipa/rulesets/IPA-104.yaml
- tools/spectral/ipa/rulesets/IPA-105.yaml
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/IPA-107.yaml
- tools/spectral/ipa/rulesets/IPA-108.yaml
- tools/spectral/ipa/rulesets/IPA-110.yaml
- tools/spectral/ipa/rulesets/IPA-114.yaml
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/IPA-119.yaml
Adds aliases to IPA Spectral rulesets to minimize duplication and increase reusability of similar `given` statements. Note: Aliases cannot be inherited from other spectral files, so they must be added to each yaml
> Add Aliases to IPA Validation Rulesets

- .github/workflows/code-health-foascli.yml
- .github/workflows/code-health-tools.yml
Updates the foascli workflow to run when dependatot updates go dependencies.
> chore: run foascli code-health workflow when updating dependencies

- .github/workflows/code-health-foascli.yml
- tools/cli/Makefile
This PR updates `golangci-lint-action` to 8.0.0
> chore: updates `golangci-lint-action`

- .github/workflows/optional-spec-validations.yml
Now that IPAs are rolled out, we can re-enable running them on all envs for the optional-spec-validation action.
_Jira ticket:_ [CLOUDP-310535](https://jira.mongodb.org/browse/CLOUDP-310535)
> CLOUDP-310535: Enable IPA validation on all env FOASes

- .github/workflows/release-IPA-metrics.yml
- tools/spectral/ipa/metrics/utils/dataDumpUtils.js
Updated IPA metrics collection to use assume-role approach instead of API Keys. Tested with staging in previous [POC](https://github.com/mongodb/openapi/pull/558) and on this branch with prod
Post-merge:
- Will update wiki
- Will remove the unused API keys from the repo
_Jira ticket:_ [CLOUDP-295480](https://jira.mongodb.org/browse/CLOUDP-295480)
> CLOUDP-295480: Migrate to Assume-Role for IPA Metric Collection

- tools/spectral/ipa/rulesets/IPA-124.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA124ArrayMaxItems.js
Based on feedback there was some confusion about the max allowed value for the `maxItems` property, since "default" was mentioned, it can be confused with the openapi property `default` or that this field is set to 100 by default. 
Clarified description of rule that 100 is the recommended max size of an array, and that the `maxItems` property value should not be larger than that.
_Jira ticket:_ [CLOUDP-314000](https://jira.mongodb.org/browse/CLOUDP-314000)
> CLOUDP-314000: Clarify IPA-124 maxItems rule description

- tools/cli/internal/cli/changelog/metadata/create.go
- tools/cli/internal/cli/changelog/metadata/create_test.go
> fix: fix the changelog release

- tools/cli/internal/changelog/changelog.go
- tools/cli/internal/cli/changelog/metadata/create.go
- tools/cli/internal/cli/changelog/metadata/create_test.go
CLOUDP-311382
This PR proposes the following changes:
- updates the `foas changelog metadata create` to consider upcoming API version when generating the metadata file
- updates the `foas changelog create` to skip upcoming api version when generating the changelog. The support will be added in CLOUDP-315486
I will test the changes once the PR is merged by running the FOAS release. I may have to create follow up PRs to fix the release flow.
> CLOUDP-311382: Update `foas changelog metadata` command to support `upcoming`

- tools/cli/internal/openapi/openapi.go
CLOUDP-325047:
Related to https://github.com/10gen/mms/pull/131979, bump recently added support for a custom extension. Here I am adding the support for extensions to the struct we use to represent an open api spec.
> CLOUDP-325047: add support for extension in the main element of the OAS

- .github/workflows/code-health-foascli.yml
This PR removes windows from the OSes where we run unit tests since we don't release foascli for windows
> ci: remove windows unit test

- .github/workflows/release-spec.yml
This pull request updates the `.github/workflows/release-spec.yml` file to improve the logic for determining when API specification changes should trigger a release to Bump.sh. The changes introduce a new check to ensure that only significant modifications to the `v2.json` file (beyond minor metadata updates) result in a release.
* Added a new step, `Check if changes should be deployed to bump.sh`, to analyze the number of changed lines in the `openapi/v2.json` file. This ensures that minor updates, such as metadata changes, do not trigger a release. (`[.github/workflows/release-spec.ymlR160-R175](diffhunk://#diff-aea44faec3c0b85ba535263f9b540a317c4ab32d8a8c221871a5b231fc4468b1R160-R175)`)
* Updated the `outputs` section to include a new `bump_release` output, which reflects whether …
> ci: deploy bump.sh spec only when there are relevant spec changes

- .github/workflows/release-spec.yml
This pull request includes a small change to the `.github/workflows/release-spec.yml` file. The change ensures that the `changed_lines` variable defaults to `0` if it is empty, improving the robustness of the release workflow.
> fix:  handle scenario when there are no changes in v2.json

- package.json
Fix : https://github.com/mongodb/openapi/security/dependabot/6
> A vulnerability was found in juliangruber brace-expansion up to 1.1.11/2.0.1/3.0.0/4.0.0. It has been rated as problematic. Affected by this issue is the function expand of the file index.js. The manipulation leads to inefficient regular expression complexity. The attack may be launched remotely. The complexity of an attack is rather high. The exploitation is known to be difficult. The exploit has been disclosed to the public and may be used. Upgrading to version 1.1.12, 2.0.2, 3.0.1 and 4.0.1 is able to address this issue. The name of the patch is a5b98a4f30d7813266b221435e1eaaf25a1b0ac5. It is recommended to upgrade the affected component.
> fix: ping brace-expansion to latest version

- README.md
- tools/README.md
- tools/spectral/README.md
- tools/spectral/ipa/README.md
- tools/spectral/ipa/rulesets/IPA-005.yaml
- tools/spectral/ipa/rulesets/IPA-102.yaml
- tools/spectral/ipa/rulesets/IPA-104.yaml
- tools/spectral/ipa/rulesets/IPA-105.yaml
- tools/spectral/ipa/rulesets/IPA-106.yaml
- tools/spectral/ipa/rulesets/IPA-107.yaml
- tools/spectral/ipa/rulesets/IPA-108.yaml
- tools/spectral/ipa/rulesets/IPA-109.yaml
- tools/spectral/ipa/rulesets/IPA-110.yaml
- tools/spectral/ipa/rulesets/IPA-112.yaml
- tools/spectral/ipa/rulesets/IPA-113.yaml
- tools/spectral/ipa/rulesets/IPA-114.yaml
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/IPA-118.yaml
- tools/spectral/ipa/rulesets/IPA-119.yaml
- tools/spectral/ipa/rulesets/IPA-121.yaml
- tools/spectral/ipa/rulesets/IPA-123.yaml
- tools/spectral/ipa/rulesets/IPA-124.yaml
- tools/spectral/ipa/rulesets/IPA-125.yaml
- tools/spectral/ipa/rulesets/IPA-126.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/scripts/generateRulesetReadme.js
Changed all internal IPA links to point to [IPA Github Pages](https://mongodb.github.io/ipa/) in anticipation of the IPA Validation Framework being [published as a public NPM package](https://docs.google.com/document/d/1DfMPa4az_jOOTknrNdqLo9dTmPypxLxWRSmCvRwye18/edit?usp=sharing). 
_Jira ticket:_ [CLOUDP-329982](https://jira.mongodb.org/browse/CLOUDP-329982)
> CLOUDP 329982: Documentation changes to public IPA links

- tools/spectral/ipa/__tests__/utils/operationIdGeneration.test.js
- tools/spectral/ipa/rulesets/functions/utils/operationIdGeneration.js
Debug for legacy custom methods case 
_Jira ticket:_ [CLOUDP-328313](https://jira.mongodb.org/browse/CLOUDP-328313)
> CLOUDP-328313: Quickfix for legacy custom methods

- tools/spectral/ipa/__tests__/utils/extensions.test.js
- tools/spectral/ipa/__tests__/utils/operationIdGeneration.test.js
- tools/spectral/ipa/__tests__/utils/validations/validateOperationIdAndReturnErrors.test.js
- tools/spectral/ipa/rulesets/functions/IPA104ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA105ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA106ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA107ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA108ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA109ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/utils/extensions.js
- tools/spectral/ipa/rulesets/functions/utils/operationIdGeneration.js
- tools/spectral/ipa/rulesets/functions/utils/validations/validateOperationIdAndReturnErrors.js
_Jira ticket:_ [CLOUDP-331821](https://jira.mongodb.org/browse/CLOUDP-331821)
Adding support for operation ID override validation. Errors are returned when:
- Operation ID is too long and there is no op ID override
- Operation ID is good length but there is also an op ID override
- When the op ID override is invalid:
- Override is too long
- Override doesn't start or end with expected words, and contains words not present in the long op ID
Moved the operation ID validation logic to a shared validation function called by each rule.
Added try catches to each rule in case of spectral errors.
Refactored custom method rule approach to apply to each operation instead of each path in the OAS.
Added unit tests for each introduced function.
The rules are not yet enabled. This will be done with E2E …
> CLOUDP-331821: Add op ID override validation

- .github/workflows/semantic-commit.yml
In order to prevent this check from failing for dependabot it should allow PR title subjects to begin with lowercase letters.
> fix: make check on PR titles more lenient

- tools/spectral/ipa/__tests__/utils/validations/validateOperationIdAndReturnErrors.test.js
- tools/spectral/ipa/rulesets/functions/IPA104ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA105ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA106ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA107ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/IPA108ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/utils/extensions.js
- tools/spectral/ipa/rulesets/functions/utils/validations/validateOperationIdAndReturnErrors.js
Following [discussions](https://docs.google.com/document/d/14H3FIJMO79zuqSPTGPwqXze7_TyQUsKdHuywiwVk4RY/edit?tab=t.0#heading=h.dssie6h3wy7x) on accommodating customer experience with Operation ID overrides, the logic has been updated to:
- **Support `x-xgen-method-verb-override` usage on non-custom methods** This change allows for nouns that do not appear in the resource path to be included in the Operation ID. ie: `getGroupStream` -> `getGroupStreamInstance`
- **Allow `x-xgen-operation-id-override` to be present on any length of Operation Id.** This override is still required for ids of length > 4, but now it can also be used to change shorter ids. ie: `getGroupStreamInstance` -> `getStreamInstance`.
_Jira ticket:_ [CLOUDP-335029](https://jira.mongodb.org/browse/CLOUDP-335029)
> fix(ipa): Update override logic to be more lenient

- .github/workflows/ipa-release.yml
Added missing env variable for version check script. Cause for [failing test run](https://github.com/mongodb/openapi/actions/runs/16676210537).
> fix: Add missing env to IPA release workflow

- .github/workflows/ipa-release.yml
Update ipa release workflow to trigger on dispatch regardless of version change, or on push when version is changed.
> ci: update ipa release to allow workflow dispatch

- .github/workflows/ipa-release.yml
Rename to be correct for ipa release npm token :-)
> ci: fix ipa npm token name in workflow

- tools/spectral/ipa/__tests__/utils/collectionUtils.test.js
- tools/spectral/ipa/ipa-spectral.yaml
- tools/spectral/ipa/rulesets/functions/IPA005ExceptionExtensionFormat.js
- tools/spectral/ipa/rulesets/functions/IPA102CollectionIdentifierCamelCase.js
- tools/spectral/ipa/rulesets/functions/IPA102CollectionIdentifierPattern.js
- tools/spectral/ipa/rulesets/functions/IPA102EachPathAlternatesBetweenResourceNameAndPathParam.js
- tools/spectral/ipa/rulesets/functions/IPA104EachResourceHasGetMethod.js
- tools/spectral/ipa/rulesets/functions/IPA104GetMethodHasNoRequestBody.js
- tools/spectral/ipa/rulesets/functions/IPA104GetMethodResponseHasNoInputFields.js
- tools/spectral/ipa/rulesets/functions/IPA104GetMethodReturnsResponseSuffixedObject.js
- tools/spectral/ipa/rulesets/functions/IPA104GetMethodReturnsSingleResource.js
- tools/spectral/ipa/rulesets/functions/IPA104GetResponseCodeShouldBe200OK.js
- tools/spectral/ipa/rulesets/functions/IPA104ValidOperationID.js
- tools/spectral/ipa/rulesets/functions/utils/collectionUtils.js
This PR introduces a new helper function to handle all violations, exceptions and adoptions for a rule. 
The idea is that when violations are collected in a rule, this function gets called to handle metric collection as well as silencing violations with exceptions.
Additionally, thing brings the functionality to error if there are no violations, but the component still has exceptions. This allows us to remove unnecessary exceptions in the OAS.
For now IPA 005-104 are updated using the new helper function. I'll adjust the other IPAs in incremental follow-up PRs to keep the PRs smaller.
Finally, I'll update the OAS and remove identified exceptions that are no longer needed + remove temporary Spectral overrides.
_Jira ticket:_ [CLOUDP-307585](https://jira.mongodb.org/browse/CLOUDP-307585) …
> feat(ipa): error on unneeded exceptions IPA 005-104

- .github/workflows/ipa-release.yml
- tools/spectral/ipa/CHANGELOG.md
- tools/spectral/ipa/CONTRIBUTING.md
- tools/spectral/ipa/package.json
Release new IPA version 1.0.0
_Jira ticket:_ [CLOUDP-307585](https://jira.mongodb.org/browse/CLOUDP-307585)
> ci(ipa): release new version 1.0.0

- .github/workflows/ipa-release.yml
- tools/spectral/ipa/package.json
Noticed the tag creation was skipped if the input for `use existing tag` is undefined.
Additionally, added requirement to only create release tag if the version changed. So we don't create tags for every commit to main.
_Jira ticket:_ [CLOUDP-307585](https://jira.mongodb.org/browse/CLOUDP-307585)
> ci(ipa): fix IPA release tag creation

- tools/spectral/ipa/CHANGELOG.md
- tools/spectral/ipa/package.json
New IPA validation version:
- feat(ipa): new IPA rule xgen-IPA-125-discriminator-must-accompany-oneOf-anyOf-allOf [`#893`](https://github.com/mongodb/openapi/pull/893)
- fix(ipa): include schema descriptions in IPA117 rules [`#895`](https://github.com/mongodb/openapi/pull/895)
- Breaking change
_Jira ticket:_ CLOUDP-308542
> ci(ipa): release new version 2.0.0

- tools/spectral/ipa/__tests__/IPA117OperationSummaryFormat.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117OperationSummaryFormat.js
- tools/spectral/ipa/rulesets/functions/IPA126TagNamesShouldUseTitleCase.js
- tools/spectral/ipa/rulesets/functions/utils/casing.js
New rule xgen-IPA-117-operation-summary-format, checks that the `summary` of an operation is in Title Case. This also covers the rules that the summary should not use CommonMark or end with period.
Will follow-up with more operation summary rules, split into one rule per PR.
_Jira ticket:_ [CLOUDP-319114](https://jira.mongodb.org/browse/CLOUDP-319114)
> feat(ipa): new rule xgen-IPA-117-operation-summary-format

- tools/spectral/ipa/__tests__/IPA117OperationSummaryCreateStartsWith.test.js
- tools/spectral/ipa/__tests__/IPA117OperationSummaryDeleteStartsWith.test.js
- tools/spectral/ipa/__tests__/IPA117OperationSummaryUpdateStartsWith.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117OperationSummaryStartsWith.js
Adds new rules to check that operation summaries start with specific words:
- `xgen-IPA-117-create-operation-summary-starts-with`
- `xgen-IPA-117-update-operation-summary-starts-with`
- `xgen-IPA-117-delete-operation-summary-starts-with`
Reuses the same function as for the previously introduced `xgen-IPA-117-get-operation-summary-starts-with` with configurable allowed words.
13 new violations, will update OAS as follow-up.
_Jira ticket:_ [CLOUDP-319114](https://jira.mongodb.org/browse/CLOUDP-319114)
> feat(ipa): new rules for operation summaries starting with specific words

- tools/spectral/ipa/__tests__/IPA117OperationSummarySingleItemWording.test.js
- tools/spectral/ipa/rulesets/IPA-117.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA117OperationSummarySingleItemWording.js
Adds new rule `xgen-IPA-117-operation-summary-single-item-wording` for guideline:
> API Producers must use "One" when referring to a single item instead of "a" or "specified".
The rule checks that the `summary` property of operations does not use the words "a", "specified" or "provided"
15 violations, will fix in follow-up.
_Jira ticket:_ [CLOUDP-319114](https://jira.mongodb.org/browse/CLOUDP-319114)
> feat(ipa): new rule xgen-IPA-117-operation-summary-single-item-wording

- .github/workflows/release-spec-runner.yml
Temp disable automatic OAS release for tomorrows prod release, will run it manually and then re-enable the cron again.
_Jira ticket:_ [CLOUDP-304020](https://jira.mongodb.org/browse/CLOUDP-304020)
> ci: temp disable automatic OAS release

- .github/workflows/release-spec-runner.yml
This reverts commit df29191d92152f083c276f2ae99940e4606fc28b.
Re-enables automatic OAS releases.
> ci: Revert temp disable automatic OAS release

- tools/spectral/ipa/__tests__/IPA005ExceptionExtensionFormat.test.js
- tools/spectral/ipa/rulesets/IPA-005.yaml
- tools/spectral/ipa/rulesets/README.md
- tools/spectral/ipa/rulesets/functions/IPA005ExceptionExtensionFormat.js
Allow camelCase and numbers in rule name
_Jira ticket:_ CLOUDP-342534
> fix(ipa): Fix IPA005 rule to allow camel case and numbers in rule name

- .github/workflows/code-health-tools.yml
We had a failure for IPA metrics collection due to package update. This ensures JS tests are run on package updates so we see the failures in the dependabot PRs before merging. 
Also useful to run the tests when IPA validation ruleset package version is updated for release.
_Jira ticket:_ [CLOUDP-347188](https://jira.mongodb.org/browse/CLOUDP-347188)
> ci: ensure JS test runs on package update

- tools/cli/internal/openapi/filter/bump.go
- tools/cli/internal/openapi/filter/bump_test.go
CLOUDP-348863
Add support for custom color (yellow) for preview APIs. https://docs.bump.sh/help/specification-support/doc-badges/#custom-color
> feat(prod): Add support for custom budges for preview APIs
