mongodb/openapi

tools/cli/internal/openapi/filter/operations.go, tools/cli/internal/openapi/filter/operations_test.go
After versioning, we need to delete the x-sunset from the current content and add to the operation
=> feat: move sunset to operation after versioning

tools/cli/test/e2e/cli/cli.go, tools/cli/test/e2e/cli/split_test.go
Just ensuring we're testing different format/files for now. Later we can add more environments.
=> chore: minor e2e improvements

tools/cli/internal/openapi/file.go, tools/cli/internal/openapi/file_test.go
=> CLOUDP-261733: [FOASCLI] The JSON FOAS doesn't include the HTLM tags

.github/workflows/generate-openapi.yml, .github/workflows/optional-spec-validations.yml, .github/workflows/release-spec-prod.yml, .github/workflows/release-spec-runner.yml, .github/workflows/release-spec.yml, .github/workflows/required-spec-validations.yml
This PR adds the GH action to release DEV, QA and STAGING. I tested my PR in a fork: https://github.com/andreaangiolillo/openapi-test/actions/runs/10115049026
=> feat: Add Release workflows for DEV, QA and STAGING

tools/cli/internal/openapi/filter/README.md
=> CLOUDP-262921: Add docs about filters

.github/workflows/postman-metrics.yml
Add environment variables that fetch_forks needs to do API calls to Postman
Tested on fork.
_Jira ticket:_ CLOUDP-265464
=> CLOUDP-265464: Add environment variables to the fetch fork step

tools/cli/internal/cli/breakingchanges/exemptions/exemptions.txt, tools/cli/internal/cli/breakingchanges/exemptions/parse_test.go, tools/cli/test/data/exemptions/exemptions.txt, tools/cli/test/data/exemptions/invalid_exemptions.yaml, tools/cli/test/e2e/cli/parse_test.go, tools/cli/test/e2e/cli/split_test.go
Add e2e tests to parse command
=> chore: Add e2e for parse command

.github/workflows/release-cli.yml
We have more actions now, so worth callout it's foascli here
=> chore: update foascli release action

.github/workflows/release-postman.yml
- Add step to create issue when the conversion step fails
- Tested on fork https://github.com/Luke-Sanderson/openapi/issues/5
Requesting review from Andrea to check it is okay to create this Issue
_Jira ticket:_ CLOUDP-267259
=> CLOUDP-267259: Create issue on conversion failure

tools/postman/scripts/transform-for-api.sh
- Circular references have a real use in the OpenAPI spec but cause an error in the output of the postman collection
- Search and remove lines with the error ```"value": "<Circular reference to ... found>"```
_Jira ticket:_ CLOUDP-264590
- Using Go SDK transformations
- While this removed some of the circular dependencies it did not remove all.
- Using jq instead of sed. 
- The bodies of responses are stored as json strings in a json object so jq would only be able to remove the full body
Before:
After:
=> CLOUDP-264590: Remove circular dependencies in generated responses

tools/.tool-versions, tools/cli/go.mod
=> chore: update go to 1.22.6

.github/workflows/release-postman.yml
=> CLOUDP-267725: Rename BASE_URL to ATLAS_PROD_BASE_URL

tools/cli/internal/changelog/changelog_test.go, tools/cli/internal/changelog/merge_test.go
=> CLOUDP-267017: Move unit test to foascli

tools/postman/scripts/upload-collection.sh
Fix for previous PR https://github.com/mongodb/openapi/pull/172
Tested locally, now reruns on 400 errors
_Jira ticket:_ CLOUDP-268216
=> CLOUDP-268216: Fix incorrect curl flag

tools/postman/README.md
[View rendered readme here](https://github.com/mongodb/openapi/tree/postman-readme/tools/postman#readme)
_Jira ticket:_ [CLOUDP-269114](https://jira.mongodb.org/browse/CLOUDP-269114)
=> CLOUDP-269114: Update readme to reflect changes to fetch

.github/ISSUE_TEMPLATE/GH_ACTION_ISSUE_TEMPLATE.md, .github/workflows/release-changelog.yml, .github/workflows/release-spec-runner.yml, .github/workflows/release-spec.yml
This PR proposes the following changes:
- Update the issue creation process to add the correct issue link to the GH issue that is created in the repo
- Update the release runner to run every hour from Monday to Friday. Previously we were running also during the weekends.
=> fix: fix the failure handler and update release runner to run every hour from Monday to Friday

.github/workflows/changelog-report.yml, tools/cli/internal/cli/changelog/convert/slack.go, tools/cli/internal/cli/changelog/convert/slack_test.go
_Jira ticket:_ CLOUDP-269299
This PR updates the changelog report message to include spec correction (changes that are hidden from the changelog)
=> CLOUDP-269299: Update changelog-report to list the spec correction changes 

tools/cli/internal/changelog/merge.go, tools/cli/internal/openapi/oasdiff.go, tools/cli/internal/openapi/oasdiff_result.go, tools/cli/internal/openapi/oasdiff_test.go, tools/cli/internal/openapi/openapi.go
Reuse the `OasDiffResult` used in changelog in the merging commands so that we can extend it for different configurations
=> chore: refactor oasdiff file to reuse oasdiff result

openapi/v1-deprecated/README.md, openapi/v2/README.md
Ticket: [CLOUDP-285462](https://jira.mongodb.org/browse/CLOUDP-285462)
This PR adds the folder where we will store the v1 OAS.
=> CLOUDP-285462: [API Platform] Add v1 to mongodb/openapi

tools/postman/README.md, tools/postman/scripts/transform-for-api.sh
Jira ticket: CLOUDP-278958
Cleanup parameters. We are recommending and documenting users to use the environment. 
All parameters we have are unused and might lead to confusion.
- Generated collection locally and tested it.
=> CLOUDP-278958: Cleanup parameters

tools/spectral/ipa/rulesets/functions/eachPathAlternatesBetweenResourceNameAndPathParam.js
_Jira ticket:_ CLOUDP-271988
Fix the import file
=> CLOUDP-271988: IPA-102: Validate paths follow expected format (Little fix)

.github/workflows/generate-openapi.yml, .github/workflows/release-changelog.yml, .github/workflows/release-spec-runner.yml, .github/workflows/release-spec-v1.yml, .github/workflows/release-spec.yml
_Jira ticket:_ [CLOUDP-270507](https://jira.mongodb.org/browse/CLOUDP-270507)
=> CLOUDP-270507: Use federated credentials

.github/workflows/generate-openapi.yml, .github/workflows/optional-spec-validations.yml, .github/workflows/release-changelog.yml, .github/workflows/release-spec-v1.yml, .github/workflows/release-spec.yml
Trying to fix aws assume role setup
=> chore: Fix permissions

.github/workflows/generate-openapi.yml, .github/workflows/release-changelog.yml, .github/workflows/release-spec-runner.yml, .github/workflows/release-spec-v1.yml, .github/workflows/release-spec.yml
- Updates to use a variable instead of secret
=> fix: fed creds fix

tools/spectral/ipa/__tests__/eachCustomMethodMustBeGetOrPost.test.js, tools/spectral/ipa/__tests__/eachCustomMethodMustUseCamelCase.test.js, tools/spectral/ipa/__tests__/eachPathAlternatesBetweenResourceNameAndPathParam.test.js, tools/spectral/ipa/__tests__/eachResourceHasGetMethod.test.js
Reflect exception format changes on rule tests
=> Exception Format Fix for Rule Tests

tools/spectral/ipa/rulesets/functions/utils/resourceEvaluation.js
Refactoring IPA Validation util file `resourceEvaluation.js` for better readability
=> Refactor resourceEvaluation.js

tools/cli/go.mod
Updates the golang version to match atlascli
=> chore: Update golang version

.github/workflows/release-IPA-metrics.yml
Fix on curl command for downloading dev openapi spec file
=> Fix on IPA metrics GH workflow

tools/spectral/ipa/README.md
Adding overview README for `/tools/ipa` about what it is, how to run, testing etc.
=> Add README for /tools/ipa

tools/postman/scripts/transform-postman.js
=> CLOUDP-288870: update js transformation to align with bash one

tools/spectral/ipa/__tests__/eachResourceHasListMethod.test.js, tools/spectral/ipa/rulesets/IPA-105.yaml, tools/spectral/ipa/rulesets/README.md, tools/spectral/ipa/rulesets/functions/eachResourceHasListMethod.js
Adds rule `xgen-IPA-105-resource-has-list` and tests. 12 offenders currently, will add exceptions as follow-up.
_Jira ticket:_ [CLOUDP-304931](https://jira.mongodb.org/browse/CLOUDP-304931)
=> CLOUDP-304931: Adds xgen-IPA-105-resource-has-list

.github/workflows/release-spec-runner.yml
=> chore: update foas release to run every 2 hours from Monday to Friday

.github/workflows/optional-spec-validations.yml
Check if the env is dev, before running IPA validations check
=> Remove optional IPA validations check from non-dev environments

tools/spectral/ipa/ipa-spectral.yaml
Added some overrides which catch violations where exceptions are not possible, or violations to be addressed later.
=> Add overrides to IPA spectral

.github/copilot-instructions.md
Added additional headers for nested documentation
=> task: update headers

.github/workflows/optional-spec-validations.yml, .github/workflows/task-failure-handler.yml
_Jira ticket:_ CLOUDP-311043
This PR provides a new failure-handler workflow called task-failure-handler for tasks, and extends optional-spec-validations with it
=> CLOUDP-311043: Prevent Duplicate Issues for optional-spec-validations

.github/scripts/generateSpecMapping.js
=> fix: fix bump release for v1 spec - prod

README.md
Fixed link to CONTRIBUTING.md in README 
_Jira ticket:_ [CLOUDP-328281](https://jira.mongodb.org/browse/CLOUDP-328281)
=> CLOUDP-328281: Fixed link to Contributing.md

.github/scripts/branded_preview.sh
=> fix: error `URL_COUNT: unbound variable`

tools/spectral/ipa/CHANGELOG.md, tools/spectral/ipa/package.json
New validation version:
- feat(ipa): new rule xgen-IPA-117-operation-summary-format [`#897`](https://github.com/mongodb/openapi/pull/897) (new rule)
- fix(ipa): child path identifiers inherit parent path exceptions [`#896`](https://github.com/mongodb/openapi/pull/896)
(custom validation framework fix)
=> ci(ipa): release new version 2.1.0

tools/spectral/ipa/CHANGELOG.md, tools/spectral/ipa/package.json
New IPA version
_Jira ticket:_ [CLOUDP-339576](https://jira.mongodb.org/browse/CLOUDP-339576)
=> ci(ipa): release new version 3.3.0

tools/spectral/ipa/CHANGELOG.md, tools/spectral/ipa/package.json
New IPA validation version.
_Jira ticket:_ [CLOUDP-340284](https://jira.mongodb.org/browse/CLOUDP-340284)
=> ci(ipa): release new version 4.0.0
